services:
  gateway:
    image: ghcr.io/mibrgmv/whoami-server-gateway:latest
    ports:
      - "8080:8080"
    depends_on:
      - history-service
      - quizzes-service
      - users-service
    environment:
      HISTORY_GRPC_ADDR: history-service:50051
      QUIZZES_GRPC_ADDR: quizzes-service:50053
      USERS_GRPC_ADDR: users-service:50052

  history-service:
    image: ghcr.io/mibrgmv/whoami-server-history:latest
    ports:
      - "50051:50051"
    depends_on:
      - postgres
      - redis
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: postgres
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_SSL_MODE: Prefer
      REDIS_ADDR: redis:6379

  quizzes-service:
    image: ghcr.io/mibrgmv/whoami-server-quizzes:latest
    ports:
      - "50053:50053"
    depends_on:
      - postgres
      - redis
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: postgres
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_SSL_MODE: Prefer
      REDIS_ADDR: redis:6379

  users-service:
    image: ghcr.io/mibrgmv/whoami-server-users:latest
    ports:
      - "50052:50052"
    depends_on:
      - postgres
      - redis
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: postgres
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_SSL_MODE: Prefer
      REDIS_ADDR: redis:6379

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres-data: