// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: statistics.proto

package statisticsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StatisticsService_GetMyStatistics_FullMethodName     = "/statistics.v1.StatisticsService/GetMyStatistics"
	StatisticsService_GetUserStatistics_FullMethodName   = "/statistics.v1.StatisticsService/GetUserStatistics"
	StatisticsService_GetMyHistory_FullMethodName        = "/statistics.v1.StatisticsService/GetMyHistory"
	StatisticsService_GetDailyLeaderboard_FullMethodName = "/statistics.v1.StatisticsService/GetDailyLeaderboard"
)

// StatisticsServiceClient is the client API for StatisticsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StatisticsServiceClient interface {
	// GetMyStatistics returns the current user's statistics
	GetMyStatistics(ctx context.Context, in *GetMyStatisticsRequest, opts ...grpc.CallOption) (*UserStatistics, error)
	// GetUserStatistics returns statistics for a specific user (must be a friend)
	GetUserStatistics(ctx context.Context, in *GetUserStatisticsRequest, opts ...grpc.CallOption) (*UserStatistics, error)
	// GetMyHistory returns the current user's game history
	GetMyHistory(ctx context.Context, in *GetMyHistoryRequest, opts ...grpc.CallOption) (*GetMyHistoryResponse, error)
	// GetDailyLeaderboard returns the leaderboard for today's daily game
	GetDailyLeaderboard(ctx context.Context, in *GetDailyLeaderboardRequest, opts ...grpc.CallOption) (*GetDailyLeaderboardResponse, error)
}

type statisticsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStatisticsServiceClient(cc grpc.ClientConnInterface) StatisticsServiceClient {
	return &statisticsServiceClient{cc}
}

func (c *statisticsServiceClient) GetMyStatistics(ctx context.Context, in *GetMyStatisticsRequest, opts ...grpc.CallOption) (*UserStatistics, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserStatistics)
	err := c.cc.Invoke(ctx, StatisticsService_GetMyStatistics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticsServiceClient) GetUserStatistics(ctx context.Context, in *GetUserStatisticsRequest, opts ...grpc.CallOption) (*UserStatistics, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserStatistics)
	err := c.cc.Invoke(ctx, StatisticsService_GetUserStatistics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticsServiceClient) GetMyHistory(ctx context.Context, in *GetMyHistoryRequest, opts ...grpc.CallOption) (*GetMyHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMyHistoryResponse)
	err := c.cc.Invoke(ctx, StatisticsService_GetMyHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticsServiceClient) GetDailyLeaderboard(ctx context.Context, in *GetDailyLeaderboardRequest, opts ...grpc.CallOption) (*GetDailyLeaderboardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDailyLeaderboardResponse)
	err := c.cc.Invoke(ctx, StatisticsService_GetDailyLeaderboard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StatisticsServiceServer is the server API for StatisticsService service.
// All implementations must embed UnimplementedStatisticsServiceServer
// for forward compatibility.
type StatisticsServiceServer interface {
	// GetMyStatistics returns the current user's statistics
	GetMyStatistics(context.Context, *GetMyStatisticsRequest) (*UserStatistics, error)
	// GetUserStatistics returns statistics for a specific user (must be a friend)
	GetUserStatistics(context.Context, *GetUserStatisticsRequest) (*UserStatistics, error)
	// GetMyHistory returns the current user's game history
	GetMyHistory(context.Context, *GetMyHistoryRequest) (*GetMyHistoryResponse, error)
	// GetDailyLeaderboard returns the leaderboard for today's daily game
	GetDailyLeaderboard(context.Context, *GetDailyLeaderboardRequest) (*GetDailyLeaderboardResponse, error)
	mustEmbedUnimplementedStatisticsServiceServer()
}

// UnimplementedStatisticsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStatisticsServiceServer struct{}

func (UnimplementedStatisticsServiceServer) GetMyStatistics(context.Context, *GetMyStatisticsRequest) (*UserStatistics, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMyStatistics not implemented")
}
func (UnimplementedStatisticsServiceServer) GetUserStatistics(context.Context, *GetUserStatisticsRequest) (*UserStatistics, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserStatistics not implemented")
}
func (UnimplementedStatisticsServiceServer) GetMyHistory(context.Context, *GetMyHistoryRequest) (*GetMyHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMyHistory not implemented")
}
func (UnimplementedStatisticsServiceServer) GetDailyLeaderboard(context.Context, *GetDailyLeaderboardRequest) (*GetDailyLeaderboardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDailyLeaderboard not implemented")
}
func (UnimplementedStatisticsServiceServer) mustEmbedUnimplementedStatisticsServiceServer() {}
func (UnimplementedStatisticsServiceServer) testEmbeddedByValue()                           {}

// UnsafeStatisticsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StatisticsServiceServer will
// result in compilation errors.
type UnsafeStatisticsServiceServer interface {
	mustEmbedUnimplementedStatisticsServiceServer()
}

func RegisterStatisticsServiceServer(s grpc.ServiceRegistrar, srv StatisticsServiceServer) {
	// If the following call pancis, it indicates UnimplementedStatisticsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StatisticsService_ServiceDesc, srv)
}

func _StatisticsService_GetMyStatistics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMyStatisticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServiceServer).GetMyStatistics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatisticsService_GetMyStatistics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServiceServer).GetMyStatistics(ctx, req.(*GetMyStatisticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatisticsService_GetUserStatistics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserStatisticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServiceServer).GetUserStatistics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatisticsService_GetUserStatistics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServiceServer).GetUserStatistics(ctx, req.(*GetUserStatisticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatisticsService_GetMyHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMyHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServiceServer).GetMyHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatisticsService_GetMyHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServiceServer).GetMyHistory(ctx, req.(*GetMyHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatisticsService_GetDailyLeaderboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDailyLeaderboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServiceServer).GetDailyLeaderboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatisticsService_GetDailyLeaderboard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServiceServer).GetDailyLeaderboard(ctx, req.(*GetDailyLeaderboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StatisticsService_ServiceDesc is the grpc.ServiceDesc for StatisticsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StatisticsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "statistics.v1.StatisticsService",
	HandlerType: (*StatisticsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMyStatistics",
			Handler:    _StatisticsService_GetMyStatistics_Handler,
		},
		{
			MethodName: "GetUserStatistics",
			Handler:    _StatisticsService_GetUserStatistics_Handler,
		},
		{
			MethodName: "GetMyHistory",
			Handler:    _StatisticsService_GetMyHistory_Handler,
		},
		{
			MethodName: "GetDailyLeaderboard",
			Handler:    _StatisticsService_GetDailyLeaderboard_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "statistics.proto",
}
