keycloak:
  base_url: http://localhost:8088
  realm: myrealm
  client_id: whoami-public-client
  client_secret:

http:
  host: 0.0.0.0
  port: 8080
  mode: debug
  shutdown_timeout: 10s
  cors:
    allowed_origins: [ "*" ]
    allowed_methods: [ "GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS" ]
    allowed_headers: [ "Origin", "Content-Type", "Accept", "Authorization" ]
    expose_headers: [ ]
    allow_credentials: true
    max_age: 86400 #24h

history_service:
  host: localhost
  port: 50051

users_service:
  host: localhost
  port: 50052

quizzes_service:
  host: localhost
  port: 50053