// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: cmd/whoami/api/quiz.proto

package quiz

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_cmd_whoami_api_quiz_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_whoami_api_quiz_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_cmd_whoami_api_quiz_proto_rawDescGZIP(), []int{0}
}

type Quiz struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int64                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
	Results       []string               `protobuf:"bytes,3,rep,name=Results,proto3" json:"Results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Quiz) Reset() {
	*x = Quiz{}
	mi := &file_cmd_whoami_api_quiz_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Quiz) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Quiz) ProtoMessage() {}

func (x *Quiz) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_whoami_api_quiz_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Quiz.ProtoReflect.Descriptor instead.
func (*Quiz) Descriptor() ([]byte, []int) {
	return file_cmd_whoami_api_quiz_proto_rawDescGZIP(), []int{1}
}

func (x *Quiz) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Quiz) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Quiz) GetResults() []string {
	if x != nil {
		return x.Results
	}
	return nil
}

type GetByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int64                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByIDRequest) Reset() {
	*x = GetByIDRequest{}
	mi := &file_cmd_whoami_api_quiz_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByIDRequest) ProtoMessage() {}

func (x *GetByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_whoami_api_quiz_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByIDRequest.ProtoReflect.Descriptor instead.
func (*GetByIDRequest) Descriptor() ([]byte, []int) {
	return file_cmd_whoami_api_quiz_proto_rawDescGZIP(), []int{2}
}

func (x *GetByIDRequest) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

var File_cmd_whoami_api_quiz_proto protoreflect.FileDescriptor

var file_cmd_whoami_api_quiz_proto_rawDesc = string([]byte{
	0x0a, 0x19, 0x63, 0x6d, 0x64, 0x2f, 0x77, 0x68, 0x6f, 0x61, 0x6d, 0x69, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x71, 0x75, 0x69, 0x7a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x71, 0x75, 0x69,
	0x7a, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x46, 0x0a, 0x04, 0x51, 0x75,
	0x69, 0x7a, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x73, 0x22, 0x20, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x49, 0x44, 0x32, 0x88, 0x01, 0x0a, 0x0b, 0x51, 0x75, 0x69, 0x7a, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x23, 0x0a, 0x03, 0x41, 0x64, 0x64, 0x12, 0x0a, 0x2e, 0x71, 0x75,
	0x69, 0x7a, 0x2e, 0x51, 0x75, 0x69, 0x7a, 0x1a, 0x0a, 0x2e, 0x71, 0x75, 0x69, 0x7a, 0x2e, 0x51,
	0x75, 0x69, 0x7a, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x12, 0x25, 0x0a, 0x06, 0x47, 0x65, 0x74,
	0x41, 0x6c, 0x6c, 0x12, 0x0b, 0x2e, 0x71, 0x75, 0x69, 0x7a, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x1a, 0x0a, 0x2e, 0x71, 0x75, 0x69, 0x7a, 0x2e, 0x51, 0x75, 0x69, 0x7a, 0x22, 0x00, 0x30, 0x01,
	0x12, 0x2d, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x42, 0x79, 0x49, 0x44, 0x12, 0x14, 0x2e, 0x71, 0x75,
	0x69, 0x7a, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x0a, 0x2e, 0x71, 0x75, 0x69, 0x7a, 0x2e, 0x51, 0x75, 0x69, 0x7a, 0x22, 0x00, 0x42,
	0x24, 0x5a, 0x22, 0x77, 0x68, 0x6f, 0x61, 0x6d, 0x69, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x67, 0x65, 0x6e, 0x2f, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67,
	0x2f, 0x71, 0x75, 0x69, 0x7a, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_cmd_whoami_api_quiz_proto_rawDescOnce sync.Once
	file_cmd_whoami_api_quiz_proto_rawDescData []byte
)

func file_cmd_whoami_api_quiz_proto_rawDescGZIP() []byte {
	file_cmd_whoami_api_quiz_proto_rawDescOnce.Do(func() {
		file_cmd_whoami_api_quiz_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cmd_whoami_api_quiz_proto_rawDesc), len(file_cmd_whoami_api_quiz_proto_rawDesc)))
	})
	return file_cmd_whoami_api_quiz_proto_rawDescData
}

var file_cmd_whoami_api_quiz_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_cmd_whoami_api_quiz_proto_goTypes = []any{
	(*Empty)(nil),          // 0: quiz.Empty
	(*Quiz)(nil),           // 1: quiz.Quiz
	(*GetByIDRequest)(nil), // 2: quiz.GetByIDRequest
}
var file_cmd_whoami_api_quiz_proto_depIdxs = []int32{
	1, // 0: quiz.QuizService.Add:input_type -> quiz.Quiz
	0, // 1: quiz.QuizService.GetAll:input_type -> quiz.Empty
	2, // 2: quiz.QuizService.GetByID:input_type -> quiz.GetByIDRequest
	1, // 3: quiz.QuizService.Add:output_type -> quiz.Quiz
	1, // 4: quiz.QuizService.GetAll:output_type -> quiz.Quiz
	1, // 5: quiz.QuizService.GetByID:output_type -> quiz.Quiz
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cmd_whoami_api_quiz_proto_init() }
func file_cmd_whoami_api_quiz_proto_init() {
	if File_cmd_whoami_api_quiz_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cmd_whoami_api_quiz_proto_rawDesc), len(file_cmd_whoami_api_quiz_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cmd_whoami_api_quiz_proto_goTypes,
		DependencyIndexes: file_cmd_whoami_api_quiz_proto_depIdxs,
		MessageInfos:      file_cmd_whoami_api_quiz_proto_msgTypes,
	}.Build()
	File_cmd_whoami_api_quiz_proto = out.File
	file_cmd_whoami_api_quiz_proto_goTypes = nil
	file_cmd_whoami_api_quiz_proto_depIdxs = nil
}
