version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - nilerr
    - bodyclose
    - rowserrcheck
    - sqlclosecheck

linters-settings:
  govet:
    enable-all: true
    disable:
      - shadow
      - fieldalignment

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck

    - path: mock
      linters:
        - errcheck
        - govet
        - staticcheck
        - unused

    - path: protogen
      linters:
        - errcheck
        - govet
        - staticcheck
        - unused
