run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocritic
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    - nilerr
    - errorlint
    - bodyclose
    - contextcheck
    - noctx
    - rowserrcheck
    - sqlclosecheck
    - prealloc

linters-settings:
  govet:
    enable-all: true
    disable:
      - shadow
      - fieldalignment

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance

  goimports:
    local-prefixes: github.com/mibrgmv/whoami-server

  misspell:
    locale: US

  errorlint:
    errorf: true
    asserts: true
    comparison: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gocritic
        - unparam

    - path: mock
      linters:
        - all

    - path: protogen
      linters:
        - all
