services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: web
    ports:
      - "3000:80"
    depends_on:
      - gateway
    networks:
      - app-network

  gateway:
    build:
      context: .
      dockerfile: Dockerfile
      target: gateway
      args:
        SERVICE: gateway
    environment:
      - KEYCLOAK_BASE_URL=http://keycloak:8080

  game-service:
    build:
      context: .
      dockerfile: Dockerfile
      target: game
      args:
        SERVICE: game

  statistics-service:
    build:
      context: .
      dockerfile: Dockerfile
      target: statistics
      args:
        SERVICE: statistics
