services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile
      target: gateway
      args:
        SERVICE: gateway

  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
      target: auth
      args:
        SERVICE: auth

  quiz-service:
    build:
      context: .
      dockerfile: Dockerfile
      target: quiz
      args:
        SERVICE: quiz

  user-service:
    build:
      context: .
      dockerfile: Dockerfile
      target: user
      args:
        SERVICE: user

  history-service:
    build:
      context: .
      dockerfile: Dockerfile
      target: history
      args:
        SERVICE: history
