http:
  host: 0.0.0.0
  port: 8080
  mode: debug
  shutdown_timeout: 10s
  cors:
    allowed_origins: [ "*" ]
    allowed_methods: [ "GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS" ]
    allowed_headers: [ "Origin", "Content-Type", "Accept", "Authorization" ]
    expose_headers: [ ]
    allow_credentials: true
    max_age: 24h

metrics:
  host: 0.0.0.0
  port: 9090

game_service:
  host: localhost
  port: 50051

game_websocket:
  host: localhost
  port: 8081

statistics_service:
  host: localhost
  port: 50053

guest_secret:

keycloak:
  base_url:
  issuer_url:
  realm:
  client_id:
  client_secret:

redis:
  address: localhost:6379
  password: ""
  db: 0
  ttl: 30m

session:
  cookie_name: gordle_session
  cookie_secure: false
  callback_url: http://localhost:3000/api/v1/auth/callback
