// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: cmd/history/api/api.proto

package history

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	QuizCompletionHistoryService_Add_FullMethodName   = "/history.QuizCompletionHistoryService/Add"
	QuizCompletionHistoryService_Query_FullMethodName = "/history.QuizCompletionHistoryService/Query"
)

// QuizCompletionHistoryServiceClient is the client API for QuizCompletionHistoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QuizCompletionHistoryServiceClient interface {
	Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error)
	Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[QuizCompletionHistoryItem], error)
}

type quizCompletionHistoryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewQuizCompletionHistoryServiceClient(cc grpc.ClientConnInterface) QuizCompletionHistoryServiceClient {
	return &quizCompletionHistoryServiceClient{cc}
}

func (c *quizCompletionHistoryServiceClient) Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddResponse)
	err := c.cc.Invoke(ctx, QuizCompletionHistoryService_Add_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quizCompletionHistoryServiceClient) Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[QuizCompletionHistoryItem], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &QuizCompletionHistoryService_ServiceDesc.Streams[0], QuizCompletionHistoryService_Query_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[QueryRequest, QuizCompletionHistoryItem]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type QuizCompletionHistoryService_QueryClient = grpc.ServerStreamingClient[QuizCompletionHistoryItem]

// QuizCompletionHistoryServiceServer is the server API for QuizCompletionHistoryService service.
// All implementations must embed UnimplementedQuizCompletionHistoryServiceServer
// for forward compatibility.
type QuizCompletionHistoryServiceServer interface {
	Add(context.Context, *AddRequest) (*AddResponse, error)
	Query(*QueryRequest, grpc.ServerStreamingServer[QuizCompletionHistoryItem]) error
	mustEmbedUnimplementedQuizCompletionHistoryServiceServer()
}

// UnimplementedQuizCompletionHistoryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQuizCompletionHistoryServiceServer struct{}

func (UnimplementedQuizCompletionHistoryServiceServer) Add(context.Context, *AddRequest) (*AddResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedQuizCompletionHistoryServiceServer) Query(*QueryRequest, grpc.ServerStreamingServer[QuizCompletionHistoryItem]) error {
	return status.Errorf(codes.Unimplemented, "method Query not implemented")
}
func (UnimplementedQuizCompletionHistoryServiceServer) mustEmbedUnimplementedQuizCompletionHistoryServiceServer() {
}
func (UnimplementedQuizCompletionHistoryServiceServer) testEmbeddedByValue() {}

// UnsafeQuizCompletionHistoryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QuizCompletionHistoryServiceServer will
// result in compilation errors.
type UnsafeQuizCompletionHistoryServiceServer interface {
	mustEmbedUnimplementedQuizCompletionHistoryServiceServer()
}

func RegisterQuizCompletionHistoryServiceServer(s grpc.ServiceRegistrar, srv QuizCompletionHistoryServiceServer) {
	// If the following call pancis, it indicates UnimplementedQuizCompletionHistoryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&QuizCompletionHistoryService_ServiceDesc, srv)
}

func _QuizCompletionHistoryService_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuizCompletionHistoryServiceServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuizCompletionHistoryService_Add_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuizCompletionHistoryServiceServer).Add(ctx, req.(*AddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuizCompletionHistoryService_Query_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(QueryRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(QuizCompletionHistoryServiceServer).Query(m, &grpc.GenericServerStream[QueryRequest, QuizCompletionHistoryItem]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type QuizCompletionHistoryService_QueryServer = grpc.ServerStreamingServer[QuizCompletionHistoryItem]

// QuizCompletionHistoryService_ServiceDesc is the grpc.ServiceDesc for QuizCompletionHistoryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QuizCompletionHistoryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "history.QuizCompletionHistoryService",
	HandlerType: (*QuizCompletionHistoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _QuizCompletionHistoryService_Add_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Query",
			Handler:       _QuizCompletionHistoryService_Query_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "cmd/history/api/api.proto",
}
