networks:
  app-network:
    driver: bridge
  keycloak-network:
    driver: bridge

volumes:
  postgres-quiz-data:
  postgres-history-data:
  postgres-keycloak-data:
  prometheus-data:
  grafana-data:

services:
  gateway:
    image: ghcr.io/${GITHUB_OWNER}/gateway:${IMAGE_TAG}
    container_name: gateway
    ports:
      - "8080:8080"
      - "9090:9090"
    depends_on:
      - auth-service
      - quiz-service
      - user-service
      - history-service
    networks:
      - app-network
    environment:
      - HTTP_MODE=${HTTP_MODE}
      - AUTH_SERVICE_HOST=auth-service
      - QUIZ_SERVICE_HOST=quiz-service
      - USER_SERVICE_HOST=user-service
      - HISTORY_SERVICE_HOST=history-service
      - KEYCLOAK_BASE_URL=${KEYCLOAK_BASE_URL}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
    restart: unless-stopped

  auth-service:
    image: ghcr.io/${GITHUB_OWNER}/auth:${IMAGE_TAG}
    container_name: auth-service
    ports:
      - "50055:50055"
    networks:
      - app-network
    environment:
      - GRPC_HOST=0.0.0.0
      - KEYCLOAK_BASE_URL=${KEYCLOAK_BASE_URL}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - KEYCLOAK_PUBLIC_CLIENT_ID=${KEYCLOAK_PUBLIC_CLIENT_ID}
      - KEYCLOAK_PUBLIC_CLIENT_SECRET=${KEYCLOAK_PUBLIC_CLIENT_SECRET}
      - KEYCLOAK_ADMIN_CLIENT_ID=${KEYCLOAK_ADMIN_CLIENT_ID}
      - KEYCLOAK_ADMIN_CLIENT_SECRET=${KEYCLOAK_ADMIN_CLIENT_SECRET}
    restart: unless-stopped

  quiz-service:
    image: ghcr.io/${GITHUB_OWNER}/quiz:${IMAGE_TAG}
    container_name: quiz-service
    ports:
      - "50051:50051"
    depends_on:
      - postgres-quiz
      - redis
    networks:
      - app-network
    environment:
      - POSTGRES_HOST=postgres-quiz
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - GRPC_HOST=0.0.0.0
      - REDIS_ADDRESS=redis:6379
      - HISTORY_SERVICE_HOST=history-service
    restart: unless-stopped

  user-service:
    image: ghcr.io/${GITHUB_OWNER}/user:${IMAGE_TAG}
    container_name: user-service
    ports:
      - "50052:50052"
    networks:
      - app-network
    environment:
      - GRPC_HOST=0.0.0.0
      - KEYCLOAK_BASE_URL=${KEYCLOAK_BASE_URL}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - KEYCLOAK_PUBLIC_CLIENT_ID=${KEYCLOAK_PUBLIC_CLIENT_ID}
      - KEYCLOAK_PUBLIC_CLIENT_SECRET=${KEYCLOAK_PUBLIC_CLIENT_SECRET}
      - KEYCLOAK_ADMIN_CLIENT_ID=${KEYCLOAK_ADMIN_CLIENT_ID}
      - KEYCLOAK_ADMIN_CLIENT_SECRET=${KEYCLOAK_ADMIN_CLIENT_SECRET}
    restart: unless-stopped

  history-service:
    image: ghcr.io/${GITHUB_OWNER}/history:${IMAGE_TAG}
    container_name: history-service
    ports:
      - "50053:50053"
    depends_on:
      - postgres-history
      - redis
      - quiz-service
    networks:
      - app-network
    environment:
      - POSTGRES_HOST=postgres-history
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - GRPC_HOST=0.0.0.0
    restart: unless-stopped

  postgres-quiz:
    image: postgres:18-alpine
    container_name: postgres-quiz
    ports:
      - "5432:5432"
    networks:
      - app-network
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    volumes:
      - postgres-quiz-data:/var/lib/postgresql/data
    restart: unless-stopped

  postgres-history:
    image: postgres:18-alpine
    container_name: postgres-history
    ports:
      - "5433:5432"
    networks:
      - app-network
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    volumes:
      - postgres-history-data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:8-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network
    restart: unless-stopped

  keycloak:
    profiles: [ "keycloak" ]
    image: quay.io/keycloak/keycloak:26.4
    container_name: keycloak
    ports:
      - "8088:8080"
    networks:
      - app-network
      - keycloak-network
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres-keycloak:5432/keycloak
      - KC_DB_USERNAME=${KEYCLOAK_DB_USERNAME}
      - KC_DB_PASSWORD=${KEYCLOAK_DB_PASSWORD}
    command: [ "start-dev" ]
    depends_on:
      - postgres-keycloak
    restart: unless-stopped

  postgres-keycloak:
    profiles: [ "keycloak" ]
    image: postgres:18-alpine
    container_name: postgres-keycloak
    networks:
      - keycloak-network
    environment:
      - POSTGRES_USER=${KEYCLOAK_DB_USERNAME}
      - POSTGRES_PASSWORD=${KEYCLOAK_DB_PASSWORD}
      - POSTGRES_DB=keycloak
    volumes:
      - postgres-keycloak-data:/var/lib/postgresql/data
    restart: unless-stopped

  prometheus:
    profiles: [ "monitoring" ]
    image: prom/prometheus:v3.8.0
    container_name: prometheus
    ports:
      - "9000:9090"
    networks:
      - app-network
    volumes:
      - ../../monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: unless-stopped

  grafana:
    profiles: [ "monitoring" ]
    image: grafana/grafana:12.2
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana-data:/var/lib/grafana
      - ../../monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ../../monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus
    restart: unless-stopped
