name: Test Go
description: Run tests with coverage

inputs:
  module:
    description: Path to Go module
    required: true
  go-version:
    description: Go version
    required: false
    default: '1.24'
  upload-coverage:
    description: Upload coverage to Codecov
    required: false
    default: 'true'
  codecov-token:
    description: Codecov token
    required: false

runs:
  using: composite
  steps:
    - uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.go-version }}
        cache-dependency-path: ${{ inputs.module }}/go.sum

    - name: Run tests
      shell: bash
      working-directory: ${{ inputs.module }}
      run: go test -v -race -coverprofile=coverage.out -covermode=atomic ./...

    - name: Upload coverage
      if: inputs.upload-coverage == 'true'
      uses: codecov/codecov-action@v4
      with:
        files: ${{ inputs.module }}/coverage.out
        flags: ${{ inputs.module }}
        fail_ci_if_error: false
      env:
        CODECOV_TOKEN: ${{ inputs.codecov-token }}
