grpc:
  host: localhost
  port: 50051

postgres:
  host: localhost
  port: 5432
  database: postgres
  username: postgres
  password: postgres
  ssl_mode: prefer

redis:
  address: "localhost:6379"
  password: ""
  db: 0
  ttl_minutes: 15

history-service:
  host: localhost
  port: 50053