// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v5.29.3
// source: game_completed.proto

package statisticsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GameCompletedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	GameMode      string                 `protobuf:"bytes,3,opt,name=game_mode,json=gameMode,proto3" json:"game_mode,omitempty"`
	GameDate      string                 `protobuf:"bytes,4,opt,name=game_date,json=gameDate,proto3" json:"game_date,omitempty"`
	TargetWord    string                 `protobuf:"bytes,5,opt,name=target_word,json=targetWord,proto3" json:"target_word,omitempty"`
	Guesses       []string               `protobuf:"bytes,6,rep,name=guesses,proto3" json:"guesses,omitempty"`
	Result        string                 `protobuf:"bytes,7,opt,name=result,proto3" json:"result,omitempty"`
	AttemptsUsed  int32                  `protobuf:"varint,8,opt,name=attempts_used,json=attemptsUsed,proto3" json:"attempts_used,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameCompletedEvent) Reset() {
	*x = GameCompletedEvent{}
	mi := &file_game_completed_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameCompletedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameCompletedEvent) ProtoMessage() {}

func (x *GameCompletedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_game_completed_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameCompletedEvent.ProtoReflect.Descriptor instead.
func (*GameCompletedEvent) Descriptor() ([]byte, []int) {
	return file_game_completed_proto_rawDescGZIP(), []int{0}
}

func (x *GameCompletedEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GameCompletedEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GameCompletedEvent) GetGameMode() string {
	if x != nil {
		return x.GameMode
	}
	return ""
}

func (x *GameCompletedEvent) GetGameDate() string {
	if x != nil {
		return x.GameDate
	}
	return ""
}

func (x *GameCompletedEvent) GetTargetWord() string {
	if x != nil {
		return x.TargetWord
	}
	return ""
}

func (x *GameCompletedEvent) GetGuesses() []string {
	if x != nil {
		return x.Guesses
	}
	return nil
}

func (x *GameCompletedEvent) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *GameCompletedEvent) GetAttemptsUsed() int32 {
	if x != nil {
		return x.AttemptsUsed
	}
	return 0
}

var File_game_completed_proto protoreflect.FileDescriptor

const file_game_completed_proto_rawDesc = "" +
	"\n" +
	"\x14game_completed.proto\x12\rstatistics.v1\"\xfe\x01\n" +
	"\x12GameCompletedEvent\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tgame_mode\x18\x03 \x01(\tR\bgameMode\x12\x1b\n" +
	"\tgame_date\x18\x04 \x01(\tR\bgameDate\x12\x1f\n" +
	"\vtarget_word\x18\x05 \x01(\tR\n" +
	"targetWord\x12\x18\n" +
	"\aguesses\x18\x06 \x03(\tR\aguesses\x12\x16\n" +
	"\x06result\x18\a \x01(\tR\x06result\x12#\n" +
	"\rattempts_used\x18\b \x01(\x05R\fattemptsUsedB;Z9gordle/statistics/pkg/protogen/statistics/v1;statisticsv1b\x06proto3"

var (
	file_game_completed_proto_rawDescOnce sync.Once
	file_game_completed_proto_rawDescData []byte
)

func file_game_completed_proto_rawDescGZIP() []byte {
	file_game_completed_proto_rawDescOnce.Do(func() {
		file_game_completed_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_game_completed_proto_rawDesc), len(file_game_completed_proto_rawDesc)))
	})
	return file_game_completed_proto_rawDescData
}

var file_game_completed_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_game_completed_proto_goTypes = []any{
	(*GameCompletedEvent)(nil), // 0: statistics.v1.GameCompletedEvent
}
var file_game_completed_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_game_completed_proto_init() }
func file_game_completed_proto_init() {
	if File_game_completed_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_game_completed_proto_rawDesc), len(file_game_completed_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_game_completed_proto_goTypes,
		DependencyIndexes: file_game_completed_proto_depIdxs,
		MessageInfos:      file_game_completed_proto_msgTypes,
	}.Build()
	File_game_completed_proto = out.File
	file_game_completed_proto_goTypes = nil
	file_game_completed_proto_depIdxs = nil
}
