name: Lint Go
description: Run golangci-lint on Go module

inputs:
  module:
    description: Path to Go module
    required: true
  go-version:
    description: Go version
    required: false
    default: '1.24'

runs:
  using: composite
  steps:
    - uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.go-version }}
        cache-dependency-path: ${{ inputs.module }}/go.sum

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: latest
        working-directory: ${{ inputs.module }}
        args: --timeout=5m
