http:
  host: 0.0.0.0
  port: 8080
  mode: debug
  shutdown_timeout: 10s
  cors:
    allowed_origins: [ "*" ]
    allowed_methods: [ "GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS" ]
    allowed_headers: [ "Origin", "Content-Type", "Accept", "Authorization" ]
    expose_headers: [ ]
    allow_credentials: true
    max_age: 86400 #24h

quizzes_service:
  host: localhost
  port: 50051

history_service:
  host: localhost
  port: 50053

keycloak:
  base_url:
  realm:
  public_client_id:
  public_client_secret:
  admin_client_id:
  admin_client_secret:
