// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: cmd/whoami/api/question.proto

package question

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_cmd_whoami_api_question_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_whoami_api_question_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_cmd_whoami_api_question_proto_rawDescGZIP(), []int{0}
}

type Question struct {
	state          protoimpl.MessageState    `protogen:"open.v1"`
	ID             int64                     `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	QuizID         int64                     `protobuf:"varint,2,opt,name=QuizID,proto3" json:"QuizID,omitempty"`
	Body           string                    `protobuf:"bytes,3,opt,name=Body,proto3" json:"Body,omitempty"`
	OptionsWeights map[string]*OptionWeights `protobuf:"bytes,4,rep,name=OptionsWeights,proto3" json:"OptionsWeights,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Question) Reset() {
	*x = Question{}
	mi := &file_cmd_whoami_api_question_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Question) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Question) ProtoMessage() {}

func (x *Question) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_whoami_api_question_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Question.ProtoReflect.Descriptor instead.
func (*Question) Descriptor() ([]byte, []int) {
	return file_cmd_whoami_api_question_proto_rawDescGZIP(), []int{1}
}

func (x *Question) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Question) GetQuizID() int64 {
	if x != nil {
		return x.QuizID
	}
	return 0
}

func (x *Question) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Question) GetOptionsWeights() map[string]*OptionWeights {
	if x != nil {
		return x.OptionsWeights
	}
	return nil
}

type OptionWeights struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Weights       []float32              `protobuf:"fixed32,1,rep,packed,name=Weights,proto3" json:"Weights,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptionWeights) Reset() {
	*x = OptionWeights{}
	mi := &file_cmd_whoami_api_question_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionWeights) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionWeights) ProtoMessage() {}

func (x *OptionWeights) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_whoami_api_question_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptionWeights.ProtoReflect.Descriptor instead.
func (*OptionWeights) Descriptor() ([]byte, []int) {
	return file_cmd_whoami_api_question_proto_rawDescGZIP(), []int{2}
}

func (x *OptionWeights) GetWeights() []float32 {
	if x != nil {
		return x.Weights
	}
	return nil
}

type Quiz struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int64                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
	Results       []string               `protobuf:"bytes,3,rep,name=Results,proto3" json:"Results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Quiz) Reset() {
	*x = Quiz{}
	mi := &file_cmd_whoami_api_question_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Quiz) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Quiz) ProtoMessage() {}

func (x *Quiz) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_whoami_api_question_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Quiz.ProtoReflect.Descriptor instead.
func (*Quiz) Descriptor() ([]byte, []int) {
	return file_cmd_whoami_api_question_proto_rawDescGZIP(), []int{3}
}

func (x *Quiz) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Quiz) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Quiz) GetResults() []string {
	if x != nil {
		return x.Results
	}
	return nil
}

type Answer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuizID        int64                  `protobuf:"varint,1,opt,name=QuizID,proto3" json:"QuizID,omitempty"`
	QuestionID    int64                  `protobuf:"varint,2,opt,name=QuestionID,proto3" json:"QuestionID,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=Body,proto3" json:"Body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Answer) Reset() {
	*x = Answer{}
	mi := &file_cmd_whoami_api_question_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Answer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Answer) ProtoMessage() {}

func (x *Answer) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_whoami_api_question_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Answer.ProtoReflect.Descriptor instead.
func (*Answer) Descriptor() ([]byte, []int) {
	return file_cmd_whoami_api_question_proto_rawDescGZIP(), []int{4}
}

func (x *Answer) GetQuizID() int64 {
	if x != nil {
		return x.QuizID
	}
	return 0
}

func (x *Answer) GetQuestionID() int64 {
	if x != nil {
		return x.QuestionID
	}
	return 0
}

func (x *Answer) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type GetByQuizIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuizID        int64                  `protobuf:"varint,1,opt,name=QuizID,proto3" json:"QuizID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByQuizIDRequest) Reset() {
	*x = GetByQuizIDRequest{}
	mi := &file_cmd_whoami_api_question_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByQuizIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByQuizIDRequest) ProtoMessage() {}

func (x *GetByQuizIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_whoami_api_question_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByQuizIDRequest.ProtoReflect.Descriptor instead.
func (*GetByQuizIDRequest) Descriptor() ([]byte, []int) {
	return file_cmd_whoami_api_question_proto_rawDescGZIP(), []int{5}
}

func (x *GetByQuizIDRequest) GetQuizID() int64 {
	if x != nil {
		return x.QuizID
	}
	return 0
}

type EvaluateAnswersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Answers       []*Answer              `protobuf:"bytes,1,rep,name=Answers,proto3" json:"Answers,omitempty"`
	Quiz          *Quiz                  `protobuf:"bytes,2,opt,name=Quiz,proto3" json:"Quiz,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateAnswersRequest) Reset() {
	*x = EvaluateAnswersRequest{}
	mi := &file_cmd_whoami_api_question_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateAnswersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateAnswersRequest) ProtoMessage() {}

func (x *EvaluateAnswersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_whoami_api_question_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateAnswersRequest.ProtoReflect.Descriptor instead.
func (*EvaluateAnswersRequest) Descriptor() ([]byte, []int) {
	return file_cmd_whoami_api_question_proto_rawDescGZIP(), []int{6}
}

func (x *EvaluateAnswersRequest) GetAnswers() []*Answer {
	if x != nil {
		return x.Answers
	}
	return nil
}

func (x *EvaluateAnswersRequest) GetQuiz() *Quiz {
	if x != nil {
		return x.Quiz
	}
	return nil
}

type EvaluateAnswersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=Result,proto3" json:"Result,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=Description,proto3" json:"Description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateAnswersResponse) Reset() {
	*x = EvaluateAnswersResponse{}
	mi := &file_cmd_whoami_api_question_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateAnswersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateAnswersResponse) ProtoMessage() {}

func (x *EvaluateAnswersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_whoami_api_question_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateAnswersResponse.ProtoReflect.Descriptor instead.
func (*EvaluateAnswersResponse) Descriptor() ([]byte, []int) {
	return file_cmd_whoami_api_question_proto_rawDescGZIP(), []int{7}
}

func (x *EvaluateAnswersResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *EvaluateAnswersResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_cmd_whoami_api_question_proto protoreflect.FileDescriptor

var file_cmd_whoami_api_question_proto_rawDesc = string([]byte{
	0x0a, 0x1d, 0x63, 0x6d, 0x64, 0x2f, 0x77, 0x68, 0x6f, 0x61, 0x6d, 0x69, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x08, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x22, 0xf2, 0x01, 0x0a, 0x08, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x44, 0x12,
	0x16, 0x0a, 0x06, 0x51, 0x75, 0x69, 0x7a, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x51, 0x75, 0x69, 0x7a, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x42, 0x6f, 0x64, 0x79, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x4e, 0x0a, 0x0e, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x73, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x51,
	0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x57,
	0x65, 0x69, 0x67, 0x68, 0x74, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0e, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x73, 0x1a, 0x5a, 0x0a, 0x13, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x73, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x2d, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x73, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x29, 0x0a, 0x0d, 0x4f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x57, 0x65, 0x69, 0x67,
	0x68, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x02, 0x52, 0x07, 0x57, 0x65, 0x69, 0x67, 0x68,
	0x74, 0x73, 0x22, 0x46, 0x0a, 0x04, 0x51, 0x75, 0x69, 0x7a, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x69,
	0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x07, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x22, 0x54, 0x0a, 0x06, 0x41, 0x6e,
	0x73, 0x77, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x51, 0x75, 0x69, 0x7a, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x51, 0x75, 0x69, 0x7a, 0x49, 0x44, 0x12, 0x1e, 0x0a, 0x0a,
	0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0a, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04,
	0x42, 0x6f, 0x64, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x42, 0x6f, 0x64, 0x79,
	0x22, 0x2c, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x42, 0x79, 0x51, 0x75, 0x69, 0x7a, 0x49, 0x44, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x51, 0x75, 0x69, 0x7a, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x51, 0x75, 0x69, 0x7a, 0x49, 0x44, 0x22, 0x68,
	0x0a, 0x16, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x65, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x07, 0x41, 0x6e, 0x73, 0x77,
	0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x52, 0x07, 0x41, 0x6e, 0x73,
	0x77, 0x65, 0x72, 0x73, 0x12, 0x22, 0x0a, 0x04, 0x51, 0x75, 0x69, 0x7a, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x51, 0x75,
	0x69, 0x7a, 0x52, 0x04, 0x51, 0x75, 0x69, 0x7a, 0x22, 0x53, 0x0a, 0x17, 0x45, 0x76, 0x61, 0x6c,
	0x75, 0x61, 0x74, 0x65, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x44,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x32, 0x98, 0x02,
	0x0a, 0x0f, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x33, 0x0a, 0x03, 0x41, 0x64, 0x64, 0x12, 0x12, 0x2e, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x12, 0x2e, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e,
	0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x12, 0x31, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c,
	0x12, 0x0f, 0x2e, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x1a, 0x12, 0x2e, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x51, 0x75, 0x65,
	0x73, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x00, 0x30, 0x01, 0x12, 0x43, 0x0a, 0x0b, 0x47, 0x65, 0x74,
	0x42, 0x79, 0x51, 0x75, 0x69, 0x7a, 0x49, 0x44, 0x12, 0x1c, 0x2e, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x79, 0x51, 0x75, 0x69, 0x7a, 0x49, 0x44, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x00, 0x30, 0x01, 0x12, 0x58,
	0x0a, 0x0f, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x65, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72,
	0x73, 0x12, 0x20, 0x2e, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x45, 0x76, 0x61,
	0x6c, 0x75, 0x61, 0x74, 0x65, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x45,
	0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x65, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x28, 0x5a, 0x26, 0x77, 0x68, 0x6f, 0x61,
	0x6d, 0x69, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x67,
	0x65, 0x6e, 0x2f, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2f, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69,
	0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_cmd_whoami_api_question_proto_rawDescOnce sync.Once
	file_cmd_whoami_api_question_proto_rawDescData []byte
)

func file_cmd_whoami_api_question_proto_rawDescGZIP() []byte {
	file_cmd_whoami_api_question_proto_rawDescOnce.Do(func() {
		file_cmd_whoami_api_question_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cmd_whoami_api_question_proto_rawDesc), len(file_cmd_whoami_api_question_proto_rawDesc)))
	})
	return file_cmd_whoami_api_question_proto_rawDescData
}

var file_cmd_whoami_api_question_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_cmd_whoami_api_question_proto_goTypes = []any{
	(*Empty)(nil),                   // 0: question.Empty
	(*Question)(nil),                // 1: question.Question
	(*OptionWeights)(nil),           // 2: question.OptionWeights
	(*Quiz)(nil),                    // 3: question.Quiz
	(*Answer)(nil),                  // 4: question.Answer
	(*GetByQuizIDRequest)(nil),      // 5: question.GetByQuizIDRequest
	(*EvaluateAnswersRequest)(nil),  // 6: question.EvaluateAnswersRequest
	(*EvaluateAnswersResponse)(nil), // 7: question.EvaluateAnswersResponse
	nil,                             // 8: question.Question.OptionsWeightsEntry
}
var file_cmd_whoami_api_question_proto_depIdxs = []int32{
	8, // 0: question.Question.OptionsWeights:type_name -> question.Question.OptionsWeightsEntry
	4, // 1: question.EvaluateAnswersRequest.Answers:type_name -> question.Answer
	3, // 2: question.EvaluateAnswersRequest.Quiz:type_name -> question.Quiz
	2, // 3: question.Question.OptionsWeightsEntry.value:type_name -> question.OptionWeights
	1, // 4: question.QuestionService.Add:input_type -> question.Question
	0, // 5: question.QuestionService.GetAll:input_type -> question.Empty
	5, // 6: question.QuestionService.GetByQuizID:input_type -> question.GetByQuizIDRequest
	6, // 7: question.QuestionService.EvaluateAnswers:input_type -> question.EvaluateAnswersRequest
	1, // 8: question.QuestionService.Add:output_type -> question.Question
	1, // 9: question.QuestionService.GetAll:output_type -> question.Question
	1, // 10: question.QuestionService.GetByQuizID:output_type -> question.Question
	7, // 11: question.QuestionService.EvaluateAnswers:output_type -> question.EvaluateAnswersResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_cmd_whoami_api_question_proto_init() }
func file_cmd_whoami_api_question_proto_init() {
	if File_cmd_whoami_api_question_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cmd_whoami_api_question_proto_rawDesc), len(file_cmd_whoami_api_question_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cmd_whoami_api_question_proto_goTypes,
		DependencyIndexes: file_cmd_whoami_api_question_proto_depIdxs,
		MessageInfos:      file_cmd_whoami_api_question_proto_msgTypes,
	}.Build()
	File_cmd_whoami_api_question_proto = out.File
	file_cmd_whoami_api_question_proto_goTypes = nil
	file_cmd_whoami_api_question_proto_depIdxs = nil
}
