jwt:
  access_secret: ""
  refresh_secret: ""
  access_expiry: 10s # for demonstration purposes
  refresh_expiry: 72h

grpc:
  host: localhost
  port: 50052
postgres:
  host: "localhost"
  port: 5432
  database: postgres
  username: postgres
  password: postgres
  ssl_mode: disable

redis:
  address: "localhost:6379"
  password: ""
  db: 0
  ttl_minutes: 15