// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v5.29.3
// source: game.proto

package gamev1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GameMode represents the type of game
type GameMode int32

const (
	GameMode_GAME_MODE_UNSPECIFIED GameMode = 0
	GameMode_GAME_MODE_DAILY       GameMode = 1
	GameMode_GAME_MODE_RANDOM      GameMode = 2
)

// Enum value maps for GameMode.
var (
	GameMode_name = map[int32]string{
		0: "GAME_MODE_UNSPECIFIED",
		1: "GAME_MODE_DAILY",
		2: "GAME_MODE_RANDOM",
	}
	GameMode_value = map[string]int32{
		"GAME_MODE_UNSPECIFIED": 0,
		"GAME_MODE_DAILY":       1,
		"GAME_MODE_RANDOM":      2,
	}
)

func (x GameMode) Enum() *GameMode {
	p := new(GameMode)
	*p = x
	return p
}

func (x GameMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GameMode) Descriptor() protoreflect.EnumDescriptor {
	return file_game_proto_enumTypes[0].Descriptor()
}

func (GameMode) Type() protoreflect.EnumType {
	return &file_game_proto_enumTypes[0]
}

func (x GameMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GameMode.Descriptor instead.
func (GameMode) EnumDescriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{0}
}

// GameStatus represents the current status of a game
type GameStatus int32

const (
	GameStatus_GAME_STATUS_UNSPECIFIED GameStatus = 0
	GameStatus_GAME_STATUS_IN_PROGRESS GameStatus = 1
	GameStatus_GAME_STATUS_WON         GameStatus = 2
	GameStatus_GAME_STATUS_LOST        GameStatus = 3
)

// Enum value maps for GameStatus.
var (
	GameStatus_name = map[int32]string{
		0: "GAME_STATUS_UNSPECIFIED",
		1: "GAME_STATUS_IN_PROGRESS",
		2: "GAME_STATUS_WON",
		3: "GAME_STATUS_LOST",
	}
	GameStatus_value = map[string]int32{
		"GAME_STATUS_UNSPECIFIED": 0,
		"GAME_STATUS_IN_PROGRESS": 1,
		"GAME_STATUS_WON":         2,
		"GAME_STATUS_LOST":        3,
	}
)

func (x GameStatus) Enum() *GameStatus {
	p := new(GameStatus)
	*p = x
	return p
}

func (x GameStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GameStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_game_proto_enumTypes[1].Descriptor()
}

func (GameStatus) Type() protoreflect.EnumType {
	return &file_game_proto_enumTypes[1]
}

func (x GameStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GameStatus.Descriptor instead.
func (GameStatus) EnumDescriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{1}
}

// LetterResult represents the result of a letter in a guess
type LetterResult int32

const (
	LetterResult_LETTER_RESULT_UNSPECIFIED LetterResult = 0
	LetterResult_LETTER_RESULT_CORRECT     LetterResult = 1
	LetterResult_LETTER_RESULT_PRESENT     LetterResult = 2
	LetterResult_LETTER_RESULT_ABSENT      LetterResult = 3
)

// Enum value maps for LetterResult.
var (
	LetterResult_name = map[int32]string{
		0: "LETTER_RESULT_UNSPECIFIED",
		1: "LETTER_RESULT_CORRECT",
		2: "LETTER_RESULT_PRESENT",
		3: "LETTER_RESULT_ABSENT",
	}
	LetterResult_value = map[string]int32{
		"LETTER_RESULT_UNSPECIFIED": 0,
		"LETTER_RESULT_CORRECT":     1,
		"LETTER_RESULT_PRESENT":     2,
		"LETTER_RESULT_ABSENT":      3,
	}
)

func (x LetterResult) Enum() *LetterResult {
	p := new(LetterResult)
	*p = x
	return p
}

func (x LetterResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LetterResult) Descriptor() protoreflect.EnumDescriptor {
	return file_game_proto_enumTypes[2].Descriptor()
}

func (LetterResult) Type() protoreflect.EnumType {
	return &file_game_proto_enumTypes[2]
}

func (x LetterResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LetterResult.Descriptor instead.
func (LetterResult) EnumDescriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{2}
}

// GameSession represents an active or completed game
type GameSession struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Language      string                 `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	GameMode      GameMode               `protobuf:"varint,4,opt,name=game_mode,json=gameMode,proto3,enum=game.v1.GameMode" json:"game_mode,omitempty"`
	GameDate      string                 `protobuf:"bytes,5,opt,name=game_date,json=gameDate,proto3" json:"game_date,omitempty"` // YYYY-MM-DD for daily games
	Status        GameStatus             `protobuf:"varint,6,opt,name=status,proto3,enum=game.v1.GameStatus" json:"status,omitempty"`
	AttemptsUsed  int32                  `protobuf:"varint,7,opt,name=attempts_used,json=attemptsUsed,proto3" json:"attempts_used,omitempty"`
	MaxAttempts   int32                  `protobuf:"varint,8,opt,name=max_attempts,json=maxAttempts,proto3" json:"max_attempts,omitempty"`
	Guesses       []*Guess               `protobuf:"bytes,9,rep,name=guesses,proto3" json:"guesses,omitempty"`
	TargetWord    string                 `protobuf:"bytes,10,opt,name=target_word,json=targetWord,proto3" json:"target_word,omitempty"` // Only revealed when game is over
	StartedAt     string                 `protobuf:"bytes,11,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt   string                 `protobuf:"bytes,12,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameSession) Reset() {
	*x = GameSession{}
	mi := &file_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameSession) ProtoMessage() {}

func (x *GameSession) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameSession.ProtoReflect.Descriptor instead.
func (*GameSession) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{0}
}

func (x *GameSession) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GameSession) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GameSession) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *GameSession) GetGameMode() GameMode {
	if x != nil {
		return x.GameMode
	}
	return GameMode_GAME_MODE_UNSPECIFIED
}

func (x *GameSession) GetGameDate() string {
	if x != nil {
		return x.GameDate
	}
	return ""
}

func (x *GameSession) GetStatus() GameStatus {
	if x != nil {
		return x.Status
	}
	return GameStatus_GAME_STATUS_UNSPECIFIED
}

func (x *GameSession) GetAttemptsUsed() int32 {
	if x != nil {
		return x.AttemptsUsed
	}
	return 0
}

func (x *GameSession) GetMaxAttempts() int32 {
	if x != nil {
		return x.MaxAttempts
	}
	return 0
}

func (x *GameSession) GetGuesses() []*Guess {
	if x != nil {
		return x.Guesses
	}
	return nil
}

func (x *GameSession) GetTargetWord() string {
	if x != nil {
		return x.TargetWord
	}
	return ""
}

func (x *GameSession) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *GameSession) GetCompletedAt() string {
	if x != nil {
		return x.CompletedAt
	}
	return ""
}

// Guess represents a single guess in a game
type Guess struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Word          string                 `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
	Results       []LetterResult         `protobuf:"varint,2,rep,packed,name=results,proto3,enum=game.v1.LetterResult" json:"results,omitempty"`
	AttemptNumber int32                  `protobuf:"varint,3,opt,name=attempt_number,json=attemptNumber,proto3" json:"attempt_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Guess) Reset() {
	*x = Guess{}
	mi := &file_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Guess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Guess) ProtoMessage() {}

func (x *Guess) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Guess.ProtoReflect.Descriptor instead.
func (*Guess) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{1}
}

func (x *Guess) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

func (x *Guess) GetResults() []LetterResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *Guess) GetAttemptNumber() int32 {
	if x != nil {
		return x.AttemptNumber
	}
	return 0
}

// StartGameRequest is the request to start a new game
type StartGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          GameMode               `protobuf:"varint,1,opt,name=mode,proto3,enum=game.v1.GameMode" json:"mode,omitempty"`
	Language      string                 `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"` // 'en' or 'ru', defaults to 'en'
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartGameRequest) Reset() {
	*x = StartGameRequest{}
	mi := &file_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartGameRequest) ProtoMessage() {}

func (x *StartGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartGameRequest.ProtoReflect.Descriptor instead.
func (*StartGameRequest) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{2}
}

func (x *StartGameRequest) GetMode() GameMode {
	if x != nil {
		return x.Mode
	}
	return GameMode_GAME_MODE_UNSPECIFIED
}

func (x *StartGameRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

// SubmitGuessRequest is the request to submit a guess
type SubmitGuessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Word          string                 `protobuf:"bytes,2,opt,name=word,proto3" json:"word,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitGuessRequest) Reset() {
	*x = SubmitGuessRequest{}
	mi := &file_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitGuessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitGuessRequest) ProtoMessage() {}

func (x *SubmitGuessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitGuessRequest.ProtoReflect.Descriptor instead.
func (*SubmitGuessRequest) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{3}
}

func (x *SubmitGuessRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SubmitGuessRequest) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

// GuessResult is the result of a guess submission
type GuessResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Guess         *Guess                 `protobuf:"bytes,1,opt,name=guess,proto3" json:"guess,omitempty"`
	GameStatus    GameStatus             `protobuf:"varint,2,opt,name=game_status,json=gameStatus,proto3,enum=game.v1.GameStatus" json:"game_status,omitempty"`
	TargetWord    string                 `protobuf:"bytes,3,opt,name=target_word,json=targetWord,proto3" json:"target_word,omitempty"` // Only set if game is over
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GuessResult) Reset() {
	*x = GuessResult{}
	mi := &file_game_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuessResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuessResult) ProtoMessage() {}

func (x *GuessResult) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuessResult.ProtoReflect.Descriptor instead.
func (*GuessResult) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{4}
}

func (x *GuessResult) GetGuess() *Guess {
	if x != nil {
		return x.Guess
	}
	return nil
}

func (x *GuessResult) GetGameStatus() GameStatus {
	if x != nil {
		return x.GameStatus
	}
	return GameStatus_GAME_STATUS_UNSPECIFIED
}

func (x *GuessResult) GetTargetWord() string {
	if x != nil {
		return x.TargetWord
	}
	return ""
}

// GetGameRequest is the request to get a game session
type GetGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameRequest) Reset() {
	*x = GetGameRequest{}
	mi := &file_game_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameRequest) ProtoMessage() {}

func (x *GetGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameRequest.ProtoReflect.Descriptor instead.
func (*GetGameRequest) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{5}
}

func (x *GetGameRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// GetDailyStatusRequest is the request to check daily game status
type GetDailyStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Language      string                 `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"` // 'en' or 'ru', defaults to 'en'
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDailyStatusRequest) Reset() {
	*x = GetDailyStatusRequest{}
	mi := &file_game_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDailyStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDailyStatusRequest) ProtoMessage() {}

func (x *GetDailyStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDailyStatusRequest.ProtoReflect.Descriptor instead.
func (*GetDailyStatusRequest) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{6}
}

func (x *GetDailyStatusRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

// DailyStatus is the response for daily game status check
type DailyStatus struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	HasPlayedToday bool                   `protobuf:"varint,1,opt,name=has_played_today,json=hasPlayedToday,proto3" json:"has_played_today,omitempty"`
	SessionId      string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`   // If played, the session ID
	Status         GameStatus             `protobuf:"varint,3,opt,name=status,proto3,enum=game.v1.GameStatus" json:"status,omitempty"` // If played, the game status
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DailyStatus) Reset() {
	*x = DailyStatus{}
	mi := &file_game_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailyStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyStatus) ProtoMessage() {}

func (x *DailyStatus) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyStatus.ProtoReflect.Descriptor instead.
func (*DailyStatus) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{7}
}

func (x *DailyStatus) GetHasPlayedToday() bool {
	if x != nil {
		return x.HasPlayedToday
	}
	return false
}

func (x *DailyStatus) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *DailyStatus) GetStatus() GameStatus {
	if x != nil {
		return x.Status
	}
	return GameStatus_GAME_STATUS_UNSPECIFIED
}

// ValidateWordRequest is the request to validate a word
type ValidateWordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Word          string                 `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
	Language      string                 `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"` // 'en' or 'ru', defaults to 'en'
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateWordRequest) Reset() {
	*x = ValidateWordRequest{}
	mi := &file_game_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateWordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateWordRequest) ProtoMessage() {}

func (x *ValidateWordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateWordRequest.ProtoReflect.Descriptor instead.
func (*ValidateWordRequest) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{8}
}

func (x *ValidateWordRequest) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

func (x *ValidateWordRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

// ValidateWordResponse is the response for word validation
type ValidateWordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsValid       bool                   `protobuf:"varint,1,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateWordResponse) Reset() {
	*x = ValidateWordResponse{}
	mi := &file_game_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateWordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateWordResponse) ProtoMessage() {}

func (x *ValidateWordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateWordResponse.ProtoReflect.Descriptor instead.
func (*ValidateWordResponse) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{9}
}

func (x *ValidateWordResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

var File_game_proto protoreflect.FileDescriptor

const file_game_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"game.proto\x12\agame.v1\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xb0\x03\n" +
	"\vGameSession\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\x12.\n" +
	"\tgame_mode\x18\x04 \x01(\x0e2\x11.game.v1.GameModeR\bgameMode\x12\x1b\n" +
	"\tgame_date\x18\x05 \x01(\tR\bgameDate\x12+\n" +
	"\x06status\x18\x06 \x01(\x0e2\x13.game.v1.GameStatusR\x06status\x12#\n" +
	"\rattempts_used\x18\a \x01(\x05R\fattemptsUsed\x12!\n" +
	"\fmax_attempts\x18\b \x01(\x05R\vmaxAttempts\x12(\n" +
	"\aguesses\x18\t \x03(\v2\x0e.game.v1.GuessR\aguesses\x12\x1f\n" +
	"\vtarget_word\x18\n" +
	" \x01(\tR\n" +
	"targetWord\x12\x1d\n" +
	"\n" +
	"started_at\x18\v \x01(\tR\tstartedAt\x12!\n" +
	"\fcompleted_at\x18\f \x01(\tR\vcompletedAt\"s\n" +
	"\x05Guess\x12\x12\n" +
	"\x04word\x18\x01 \x01(\tR\x04word\x12/\n" +
	"\aresults\x18\x02 \x03(\x0e2\x15.game.v1.LetterResultR\aresults\x12%\n" +
	"\x0eattempt_number\x18\x03 \x01(\x05R\rattemptNumber\"U\n" +
	"\x10StartGameRequest\x12%\n" +
	"\x04mode\x18\x01 \x01(\x0e2\x11.game.v1.GameModeR\x04mode\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\"G\n" +
	"\x12SubmitGuessRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04word\x18\x02 \x01(\tR\x04word\"\x8a\x01\n" +
	"\vGuessResult\x12$\n" +
	"\x05guess\x18\x01 \x01(\v2\x0e.game.v1.GuessR\x05guess\x124\n" +
	"\vgame_status\x18\x02 \x01(\x0e2\x13.game.v1.GameStatusR\n" +
	"gameStatus\x12\x1f\n" +
	"\vtarget_word\x18\x03 \x01(\tR\n" +
	"targetWord\"/\n" +
	"\x0eGetGameRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"3\n" +
	"\x15GetDailyStatusRequest\x12\x1a\n" +
	"\blanguage\x18\x01 \x01(\tR\blanguage\"\x83\x01\n" +
	"\vDailyStatus\x12(\n" +
	"\x10has_played_today\x18\x01 \x01(\bR\x0ehasPlayedToday\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12+\n" +
	"\x06status\x18\x03 \x01(\x0e2\x13.game.v1.GameStatusR\x06status\"E\n" +
	"\x13ValidateWordRequest\x12\x12\n" +
	"\x04word\x18\x01 \x01(\tR\x04word\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\"1\n" +
	"\x14ValidateWordResponse\x12\x19\n" +
	"\bis_valid\x18\x01 \x01(\bR\aisValid*P\n" +
	"\bGameMode\x12\x19\n" +
	"\x15GAME_MODE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fGAME_MODE_DAILY\x10\x01\x12\x14\n" +
	"\x10GAME_MODE_RANDOM\x10\x02*q\n" +
	"\n" +
	"GameStatus\x12\x1b\n" +
	"\x17GAME_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17GAME_STATUS_IN_PROGRESS\x10\x01\x12\x13\n" +
	"\x0fGAME_STATUS_WON\x10\x02\x12\x14\n" +
	"\x10GAME_STATUS_LOST\x10\x03*}\n" +
	"\fLetterResult\x12\x1d\n" +
	"\x19LETTER_RESULT_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15LETTER_RESULT_CORRECT\x10\x01\x12\x19\n" +
	"\x15LETTER_RESULT_PRESENT\x10\x02\x12\x18\n" +
	"\x14LETTER_RESULT_ABSENT\x10\x032\xe9\x04\n" +
	"\vGameService\x12k\n" +
	"\tStartGame\x12\x19.game.v1.StartGameRequest\x1a\x14.game.v1.GameSession\"-\x92A\x12b\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/api/v1/games\x12\x84\x01\n" +
	"\vSubmitGuess\x12\x1b.game.v1.SubmitGuessRequest\x1a\x14.game.v1.GuessResult\"B\x92A\x12b\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02':\x01*\"\"/api/v1/games/{session_id}/guesses\x12q\n" +
	"\aGetGame\x12\x17.game.v1.GetGameRequest\x1a\x14.game.v1.GameSession\"7\x92A\x12b\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02\x1c\x12\x1a/api/v1/games/{session_id}\x12\x7f\n" +
	"\x0eGetDailyStatus\x12\x1e.game.v1.GetDailyStatusRequest\x1a\x14.game.v1.DailyStatus\"7\x92A\x12b\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02\x1c\x12\x1a/api/v1/games/daily/status\x12r\n" +
	"\fValidateWord\x12\x1c.game.v1.ValidateWordRequest\x1a\x1d.game.v1.ValidateWordResponse\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/api/v1/games/validate/{word}B,Z*gordle/gateway/pkg/protogen/game/v1;gamev1b\x06proto3"

var (
	file_game_proto_rawDescOnce sync.Once
	file_game_proto_rawDescData []byte
)

func file_game_proto_rawDescGZIP() []byte {
	file_game_proto_rawDescOnce.Do(func() {
		file_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_game_proto_rawDesc), len(file_game_proto_rawDesc)))
	})
	return file_game_proto_rawDescData
}

var file_game_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_game_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_game_proto_goTypes = []any{
	(GameMode)(0),                 // 0: game.v1.GameMode
	(GameStatus)(0),               // 1: game.v1.GameStatus
	(LetterResult)(0),             // 2: game.v1.LetterResult
	(*GameSession)(nil),           // 3: game.v1.GameSession
	(*Guess)(nil),                 // 4: game.v1.Guess
	(*StartGameRequest)(nil),      // 5: game.v1.StartGameRequest
	(*SubmitGuessRequest)(nil),    // 6: game.v1.SubmitGuessRequest
	(*GuessResult)(nil),           // 7: game.v1.GuessResult
	(*GetGameRequest)(nil),        // 8: game.v1.GetGameRequest
	(*GetDailyStatusRequest)(nil), // 9: game.v1.GetDailyStatusRequest
	(*DailyStatus)(nil),           // 10: game.v1.DailyStatus
	(*ValidateWordRequest)(nil),   // 11: game.v1.ValidateWordRequest
	(*ValidateWordResponse)(nil),  // 12: game.v1.ValidateWordResponse
}
var file_game_proto_depIdxs = []int32{
	0,  // 0: game.v1.GameSession.game_mode:type_name -> game.v1.GameMode
	1,  // 1: game.v1.GameSession.status:type_name -> game.v1.GameStatus
	4,  // 2: game.v1.GameSession.guesses:type_name -> game.v1.Guess
	2,  // 3: game.v1.Guess.results:type_name -> game.v1.LetterResult
	0,  // 4: game.v1.StartGameRequest.mode:type_name -> game.v1.GameMode
	4,  // 5: game.v1.GuessResult.guess:type_name -> game.v1.Guess
	1,  // 6: game.v1.GuessResult.game_status:type_name -> game.v1.GameStatus
	1,  // 7: game.v1.DailyStatus.status:type_name -> game.v1.GameStatus
	5,  // 8: game.v1.GameService.StartGame:input_type -> game.v1.StartGameRequest
	6,  // 9: game.v1.GameService.SubmitGuess:input_type -> game.v1.SubmitGuessRequest
	8,  // 10: game.v1.GameService.GetGame:input_type -> game.v1.GetGameRequest
	9,  // 11: game.v1.GameService.GetDailyStatus:input_type -> game.v1.GetDailyStatusRequest
	11, // 12: game.v1.GameService.ValidateWord:input_type -> game.v1.ValidateWordRequest
	3,  // 13: game.v1.GameService.StartGame:output_type -> game.v1.GameSession
	7,  // 14: game.v1.GameService.SubmitGuess:output_type -> game.v1.GuessResult
	3,  // 15: game.v1.GameService.GetGame:output_type -> game.v1.GameSession
	10, // 16: game.v1.GameService.GetDailyStatus:output_type -> game.v1.DailyStatus
	12, // 17: game.v1.GameService.ValidateWord:output_type -> game.v1.ValidateWordResponse
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_game_proto_init() }
func file_game_proto_init() {
	if File_game_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_game_proto_rawDesc), len(file_game_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_game_proto_goTypes,
		DependencyIndexes: file_game_proto_depIdxs,
		EnumInfos:         file_game_proto_enumTypes,
		MessageInfos:      file_game_proto_msgTypes,
	}.Build()
	File_game_proto = out.File
	file_game_proto_goTypes = nil
	file_game_proto_depIdxs = nil
}
