// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v5.29.3
// source: question.proto

package question

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OptionWeights struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Weights       []float32              `protobuf:"fixed32,1,rep,packed,name=weights,proto3" json:"weights,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptionWeights) Reset() {
	*x = OptionWeights{}
	mi := &file_question_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionWeights) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionWeights) ProtoMessage() {}

func (x *OptionWeights) ProtoReflect() protoreflect.Message {
	mi := &file_question_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptionWeights.ProtoReflect.Descriptor instead.
func (*OptionWeights) Descriptor() ([]byte, []int) {
	return file_question_proto_rawDescGZIP(), []int{0}
}

func (x *OptionWeights) GetWeights() []float32 {
	if x != nil {
		return x.Weights
	}
	return nil
}

type Question struct {
	state          protoimpl.MessageState    `protogen:"open.v1"`
	Id             string                    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	QuizId         string                    `protobuf:"bytes,2,opt,name=quiz_id,json=quizId,proto3" json:"quiz_id,omitempty"`
	Body           string                    `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	OptionsWeights map[string]*OptionWeights `protobuf:"bytes,4,rep,name=options_weights,json=optionsWeights,proto3" json:"options_weights,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Question) Reset() {
	*x = Question{}
	mi := &file_question_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Question) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Question) ProtoMessage() {}

func (x *Question) ProtoReflect() protoreflect.Message {
	mi := &file_question_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Question.ProtoReflect.Descriptor instead.
func (*Question) Descriptor() ([]byte, []int) {
	return file_question_proto_rawDescGZIP(), []int{1}
}

func (x *Question) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Question) GetQuizId() string {
	if x != nil {
		return x.QuizId
	}
	return ""
}

func (x *Question) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Question) GetOptionsWeights() map[string]*OptionWeights {
	if x != nil {
		return x.OptionsWeights
	}
	return nil
}

type CreateQuestionRequest struct {
	state          protoimpl.MessageState    `protogen:"open.v1"`
	QuizId         string                    `protobuf:"bytes,1,opt,name=quiz_id,json=quizId,proto3" json:"quiz_id,omitempty"`
	Body           string                    `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	OptionsWeights map[string]*OptionWeights `protobuf:"bytes,3,rep,name=options_weights,json=optionsWeights,proto3" json:"options_weights,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateQuestionRequest) Reset() {
	*x = CreateQuestionRequest{}
	mi := &file_question_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateQuestionRequest) ProtoMessage() {}

func (x *CreateQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_question_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateQuestionRequest.ProtoReflect.Descriptor instead.
func (*CreateQuestionRequest) Descriptor() ([]byte, []int) {
	return file_question_proto_rawDescGZIP(), []int{2}
}

func (x *CreateQuestionRequest) GetQuizId() string {
	if x != nil {
		return x.QuizId
	}
	return ""
}

func (x *CreateQuestionRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *CreateQuestionRequest) GetOptionsWeights() map[string]*OptionWeights {
	if x != nil {
		return x.OptionsWeights
	}
	return nil
}

type BatchCreateQuestionsRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	QuizId        string                   `protobuf:"bytes,1,opt,name=quiz_id,json=quizId,proto3" json:"quiz_id,omitempty"`
	Requests      []*CreateQuestionRequest `protobuf:"bytes,2,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCreateQuestionsRequest) Reset() {
	*x = BatchCreateQuestionsRequest{}
	mi := &file_question_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCreateQuestionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCreateQuestionsRequest) ProtoMessage() {}

func (x *BatchCreateQuestionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_question_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCreateQuestionsRequest.ProtoReflect.Descriptor instead.
func (*BatchCreateQuestionsRequest) Descriptor() ([]byte, []int) {
	return file_question_proto_rawDescGZIP(), []int{3}
}

func (x *BatchCreateQuestionsRequest) GetQuizId() string {
	if x != nil {
		return x.QuizId
	}
	return ""
}

func (x *BatchCreateQuestionsRequest) GetRequests() []*CreateQuestionRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

type BatchCreateQuestionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Questions     []*Question            `protobuf:"bytes,1,rep,name=questions,proto3" json:"questions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCreateQuestionsResponse) Reset() {
	*x = BatchCreateQuestionsResponse{}
	mi := &file_question_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCreateQuestionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCreateQuestionsResponse) ProtoMessage() {}

func (x *BatchCreateQuestionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_question_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCreateQuestionsResponse.ProtoReflect.Descriptor instead.
func (*BatchCreateQuestionsResponse) Descriptor() ([]byte, []int) {
	return file_question_proto_rawDescGZIP(), []int{4}
}

func (x *BatchCreateQuestionsResponse) GetQuestions() []*Question {
	if x != nil {
		return x.Questions
	}
	return nil
}

type BatchGetQuestionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuizId        string                 `protobuf:"bytes,1,opt,name=quiz_id,json=quizId,proto3" json:"quiz_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetQuestionsRequest) Reset() {
	*x = BatchGetQuestionsRequest{}
	mi := &file_question_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetQuestionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetQuestionsRequest) ProtoMessage() {}

func (x *BatchGetQuestionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_question_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetQuestionsRequest.ProtoReflect.Descriptor instead.
func (*BatchGetQuestionsRequest) Descriptor() ([]byte, []int) {
	return file_question_proto_rawDescGZIP(), []int{5}
}

func (x *BatchGetQuestionsRequest) GetQuizId() string {
	if x != nil {
		return x.QuizId
	}
	return ""
}

type BatchGetQuestionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Questions     []*QuestionResponse    `protobuf:"bytes,1,rep,name=questions,proto3" json:"questions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetQuestionsResponse) Reset() {
	*x = BatchGetQuestionsResponse{}
	mi := &file_question_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetQuestionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetQuestionsResponse) ProtoMessage() {}

func (x *BatchGetQuestionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_question_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetQuestionsResponse.ProtoReflect.Descriptor instead.
func (*BatchGetQuestionsResponse) Descriptor() ([]byte, []int) {
	return file_question_proto_rawDescGZIP(), []int{6}
}

func (x *BatchGetQuestionsResponse) GetQuestions() []*QuestionResponse {
	if x != nil {
		return x.Questions
	}
	return nil
}

type QuestionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	QuizId        string                 `protobuf:"bytes,2,opt,name=quiz_id,json=quizId,proto3" json:"quiz_id,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	Options       []string               `protobuf:"bytes,4,rep,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuestionResponse) Reset() {
	*x = QuestionResponse{}
	mi := &file_question_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestionResponse) ProtoMessage() {}

func (x *QuestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_question_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestionResponse.ProtoReflect.Descriptor instead.
func (*QuestionResponse) Descriptor() ([]byte, []int) {
	return file_question_proto_rawDescGZIP(), []int{7}
}

func (x *QuestionResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *QuestionResponse) GetQuizId() string {
	if x != nil {
		return x.QuizId
	}
	return ""
}

func (x *QuestionResponse) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *QuestionResponse) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

type Answer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuizId        string                 `protobuf:"bytes,1,opt,name=quiz_id,json=quizId,proto3" json:"quiz_id,omitempty"`
	QuestionId    string                 `protobuf:"bytes,2,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Answer) Reset() {
	*x = Answer{}
	mi := &file_question_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Answer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Answer) ProtoMessage() {}

func (x *Answer) ProtoReflect() protoreflect.Message {
	mi := &file_question_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Answer.ProtoReflect.Descriptor instead.
func (*Answer) Descriptor() ([]byte, []int) {
	return file_question_proto_rawDescGZIP(), []int{8}
}

func (x *Answer) GetQuizId() string {
	if x != nil {
		return x.QuizId
	}
	return ""
}

func (x *Answer) GetQuestionId() string {
	if x != nil {
		return x.QuestionId
	}
	return ""
}

func (x *Answer) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type EvaluateAnswersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuizId        string                 `protobuf:"bytes,1,opt,name=quiz_id,json=quizId,proto3" json:"quiz_id,omitempty"`
	Answers       []*Answer              `protobuf:"bytes,2,rep,name=answers,proto3" json:"answers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateAnswersRequest) Reset() {
	*x = EvaluateAnswersRequest{}
	mi := &file_question_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateAnswersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateAnswersRequest) ProtoMessage() {}

func (x *EvaluateAnswersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_question_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateAnswersRequest.ProtoReflect.Descriptor instead.
func (*EvaluateAnswersRequest) Descriptor() ([]byte, []int) {
	return file_question_proto_rawDescGZIP(), []int{9}
}

func (x *EvaluateAnswersRequest) GetQuizId() string {
	if x != nil {
		return x.QuizId
	}
	return ""
}

func (x *EvaluateAnswersRequest) GetAnswers() []*Answer {
	if x != nil {
		return x.Answers
	}
	return nil
}

type EvaluateAnswersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateAnswersResponse) Reset() {
	*x = EvaluateAnswersResponse{}
	mi := &file_question_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateAnswersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateAnswersResponse) ProtoMessage() {}

func (x *EvaluateAnswersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_question_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateAnswersResponse.ProtoReflect.Descriptor instead.
func (*EvaluateAnswersResponse) Descriptor() ([]byte, []int) {
	return file_question_proto_rawDescGZIP(), []int{10}
}

func (x *EvaluateAnswersResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_question_proto protoreflect.FileDescriptor

const file_question_proto_rawDesc = "" +
	"\n" +
	"\x0equestion.proto\x12\bquestion\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x15google/api/http.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\")\n" +
	"\rOptionWeights\x12\x18\n" +
	"\aweights\x18\x01 \x03(\x02R\aweights\"\xf4\x01\n" +
	"\bQuestion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\aquiz_id\x18\x02 \x01(\tR\x06quizId\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x12O\n" +
	"\x0foptions_weights\x18\x04 \x03(\v2&.question.Question.OptionsWeightsEntryR\x0eoptionsWeights\x1aZ\n" +
	"\x13OptionsWeightsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12-\n" +
	"\x05value\x18\x02 \x01(\v2\x17.question.OptionWeightsR\x05value:\x028\x01\"\xfe\x01\n" +
	"\x15CreateQuestionRequest\x12\x17\n" +
	"\aquiz_id\x18\x01 \x01(\tR\x06quizId\x12\x12\n" +
	"\x04body\x18\x02 \x01(\tR\x04body\x12\\\n" +
	"\x0foptions_weights\x18\x03 \x03(\v23.question.CreateQuestionRequest.OptionsWeightsEntryR\x0eoptionsWeights\x1aZ\n" +
	"\x13OptionsWeightsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12-\n" +
	"\x05value\x18\x02 \x01(\v2\x17.question.OptionWeightsR\x05value:\x028\x01\"s\n" +
	"\x1bBatchCreateQuestionsRequest\x12\x17\n" +
	"\aquiz_id\x18\x01 \x01(\tR\x06quizId\x12;\n" +
	"\brequests\x18\x02 \x03(\v2\x1f.question.CreateQuestionRequestR\brequests\"P\n" +
	"\x1cBatchCreateQuestionsResponse\x120\n" +
	"\tquestions\x18\x01 \x03(\v2\x12.question.QuestionR\tquestions\"3\n" +
	"\x18BatchGetQuestionsRequest\x12\x17\n" +
	"\aquiz_id\x18\x01 \x01(\tR\x06quizId\"U\n" +
	"\x19BatchGetQuestionsResponse\x128\n" +
	"\tquestions\x18\x01 \x03(\v2\x1a.question.QuestionResponseR\tquestions\"i\n" +
	"\x10QuestionResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\aquiz_id\x18\x02 \x01(\tR\x06quizId\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x12\x18\n" +
	"\aoptions\x18\x04 \x03(\tR\aoptions\"V\n" +
	"\x06Answer\x12\x17\n" +
	"\aquiz_id\x18\x01 \x01(\tR\x06quizId\x12\x1f\n" +
	"\vquestion_id\x18\x02 \x01(\tR\n" +
	"questionId\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\"]\n" +
	"\x16EvaluateAnswersRequest\x12\x17\n" +
	"\aquiz_id\x18\x01 \x01(\tR\x06quizId\x12*\n" +
	"\aanswers\x18\x02 \x03(\v2\x10.question.AnswerR\aanswers\"1\n" +
	"\x17EvaluateAnswersResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result2\xbd\x03\n" +
	"\x0fQuestionService\x12\x95\x01\n" +
	"\x14BatchCreateQuestions\x12%.question.BatchCreateQuestionsRequest\x1a&.question.BatchCreateQuestionsResponse\".\x82\xd3\xe4\x93\x02(:\x01*\"#/api/v1/quizzes/{quiz_id}/questions\x12\x89\x01\n" +
	"\x11BatchGetQuestions\x12\".question.BatchGetQuestionsRequest\x1a#.question.BatchGetQuestionsResponse\"+\x82\xd3\xe4\x93\x02%\x12#/api/v1/quizzes/{quiz_id}/questions\x12\x85\x01\n" +
	"\x0fEvaluateAnswers\x12 .question.EvaluateAnswersRequest\x1a!.question.EvaluateAnswersResponse\"-\x82\xd3\xe4\x93\x02':\x01*\"\"/api/v1/quizzes/{quiz_id}/evaluateB0Z.whoami-server-quizzes/protogen/golang/questionb\x06proto3"

var (
	file_question_proto_rawDescOnce sync.Once
	file_question_proto_rawDescData []byte
)

func file_question_proto_rawDescGZIP() []byte {
	file_question_proto_rawDescOnce.Do(func() {
		file_question_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_question_proto_rawDesc), len(file_question_proto_rawDesc)))
	})
	return file_question_proto_rawDescData
}

var file_question_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_question_proto_goTypes = []any{
	(*OptionWeights)(nil),                // 0: question.OptionWeights
	(*Question)(nil),                     // 1: question.Question
	(*CreateQuestionRequest)(nil),        // 2: question.CreateQuestionRequest
	(*BatchCreateQuestionsRequest)(nil),  // 3: question.BatchCreateQuestionsRequest
	(*BatchCreateQuestionsResponse)(nil), // 4: question.BatchCreateQuestionsResponse
	(*BatchGetQuestionsRequest)(nil),     // 5: question.BatchGetQuestionsRequest
	(*BatchGetQuestionsResponse)(nil),    // 6: question.BatchGetQuestionsResponse
	(*QuestionResponse)(nil),             // 7: question.QuestionResponse
	(*Answer)(nil),                       // 8: question.Answer
	(*EvaluateAnswersRequest)(nil),       // 9: question.EvaluateAnswersRequest
	(*EvaluateAnswersResponse)(nil),      // 10: question.EvaluateAnswersResponse
	nil,                                  // 11: question.Question.OptionsWeightsEntry
	nil,                                  // 12: question.CreateQuestionRequest.OptionsWeightsEntry
}
var file_question_proto_depIdxs = []int32{
	11, // 0: question.Question.options_weights:type_name -> question.Question.OptionsWeightsEntry
	12, // 1: question.CreateQuestionRequest.options_weights:type_name -> question.CreateQuestionRequest.OptionsWeightsEntry
	2,  // 2: question.BatchCreateQuestionsRequest.requests:type_name -> question.CreateQuestionRequest
	1,  // 3: question.BatchCreateQuestionsResponse.questions:type_name -> question.Question
	7,  // 4: question.BatchGetQuestionsResponse.questions:type_name -> question.QuestionResponse
	8,  // 5: question.EvaluateAnswersRequest.answers:type_name -> question.Answer
	0,  // 6: question.Question.OptionsWeightsEntry.value:type_name -> question.OptionWeights
	0,  // 7: question.CreateQuestionRequest.OptionsWeightsEntry.value:type_name -> question.OptionWeights
	3,  // 8: question.QuestionService.BatchCreateQuestions:input_type -> question.BatchCreateQuestionsRequest
	5,  // 9: question.QuestionService.BatchGetQuestions:input_type -> question.BatchGetQuestionsRequest
	9,  // 10: question.QuestionService.EvaluateAnswers:input_type -> question.EvaluateAnswersRequest
	4,  // 11: question.QuestionService.BatchCreateQuestions:output_type -> question.BatchCreateQuestionsResponse
	6,  // 12: question.QuestionService.BatchGetQuestions:output_type -> question.BatchGetQuestionsResponse
	10, // 13: question.QuestionService.EvaluateAnswers:output_type -> question.EvaluateAnswersResponse
	11, // [11:14] is the sub-list for method output_type
	8,  // [8:11] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_question_proto_init() }
func file_question_proto_init() {
	if File_question_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_question_proto_rawDesc), len(file_question_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_question_proto_goTypes,
		DependencyIndexes: file_question_proto_depIdxs,
		MessageInfos:      file_question_proto_msgTypes,
	}.Build()
	File_question_proto = out.File
	file_question_proto_goTypes = nil
	file_question_proto_depIdxs = nil
}
