name: Build Statistics

on:
  workflow_dispatch:
  push:
    branches: [main, dev]
    paths:
      - 'statistics/**'
      - 'libs/**'
  pull_request:
    branches: [main, dev]
    paths:
      - 'statistics/**'
      - 'libs/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build-go
        with:
          service: statistics
