name: CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      libs: ${{ steps.filter.outputs.libs }}
      gateway: ${{ steps.filter.outputs.gateway }}
      quiz: ${{ steps.filter.outputs.quiz }}
      auth: ${{ steps.filter.outputs.auth }}
      user: ${{ steps.filter.outputs.user }}
      history: ${{ steps.filter.outputs.history }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            libs:
              - 'libs/**'
              - '.golangci.yml'
              - '.github/**'
            gateway:
              - 'gateway/**'
            quiz:
              - 'quiz/**'
            auth:
              - 'auth/**'
            user:
              - 'user/**'
            history:
              - 'history/**'

  libs:
    needs: changes
    if: needs.changes.outputs.libs == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/ci-go
        with:
          working-directory: libs

  gateway:
    needs: changes
    if: needs.changes.outputs.gateway == 'true' || needs.changes.outputs.libs == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/ci-go
        with:
          working-directory: gateway

  quiz:
    needs: changes
    if: needs.changes.outputs.quiz == 'true' || needs.changes.outputs.libs == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/ci-go
        with:
          working-directory: quiz

  auth:
    needs: changes
    if: needs.changes.outputs.auth == 'true' || needs.changes.outputs.libs == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/ci-go
        with:
          working-directory: auth

  user:
    needs: changes
    if: needs.changes.outputs.user == 'true' || needs.changes.outputs.libs == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/ci-go
        with:
          working-directory: user

  history:
    needs: changes
    if: needs.changes.outputs.history == 'true' || needs.changes.outputs.libs == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/ci-go
        with:
          working-directory: history
