// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v5.29.3
// source: room.proto

package roomv1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RoomMode represents the type of multiplayer game
type RoomMode int32

const (
	RoomMode_ROOM_MODE_UNSPECIFIED  RoomMode = 0
	RoomMode_ROOM_MODE_SINGLE_ROUND RoomMode = 1
	RoomMode_ROOM_MODE_MARATHON     RoomMode = 2
)

// Enum value maps for RoomMode.
var (
	RoomMode_name = map[int32]string{
		0: "ROOM_MODE_UNSPECIFIED",
		1: "ROOM_MODE_SINGLE_ROUND",
		2: "ROOM_MODE_MARATHON",
	}
	RoomMode_value = map[string]int32{
		"ROOM_MODE_UNSPECIFIED":  0,
		"ROOM_MODE_SINGLE_ROUND": 1,
		"ROOM_MODE_MARATHON":     2,
	}
)

func (x RoomMode) Enum() *RoomMode {
	p := new(RoomMode)
	*p = x
	return p
}

func (x RoomMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoomMode) Descriptor() protoreflect.EnumDescriptor {
	return file_room_proto_enumTypes[0].Descriptor()
}

func (RoomMode) Type() protoreflect.EnumType {
	return &file_room_proto_enumTypes[0]
}

func (x RoomMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoomMode.Descriptor instead.
func (RoomMode) EnumDescriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{0}
}

// RoomStatus represents the current status of a room
type RoomStatus int32

const (
	RoomStatus_ROOM_STATUS_UNSPECIFIED RoomStatus = 0
	RoomStatus_ROOM_STATUS_WAITING     RoomStatus = 1
	RoomStatus_ROOM_STATUS_PLAYING     RoomStatus = 2
	RoomStatus_ROOM_STATUS_FINISHED    RoomStatus = 3
)

// Enum value maps for RoomStatus.
var (
	RoomStatus_name = map[int32]string{
		0: "ROOM_STATUS_UNSPECIFIED",
		1: "ROOM_STATUS_WAITING",
		2: "ROOM_STATUS_PLAYING",
		3: "ROOM_STATUS_FINISHED",
	}
	RoomStatus_value = map[string]int32{
		"ROOM_STATUS_UNSPECIFIED": 0,
		"ROOM_STATUS_WAITING":     1,
		"ROOM_STATUS_PLAYING":     2,
		"ROOM_STATUS_FINISHED":    3,
	}
)

func (x RoomStatus) Enum() *RoomStatus {
	p := new(RoomStatus)
	*p = x
	return p
}

func (x RoomStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoomStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_room_proto_enumTypes[1].Descriptor()
}

func (RoomStatus) Type() protoreflect.EnumType {
	return &file_room_proto_enumTypes[1]
}

func (x RoomStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoomStatus.Descriptor instead.
func (RoomStatus) EnumDescriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{1}
}

// PlayerStatus represents the current status of a player in a room
type PlayerStatus int32

const (
	PlayerStatus_PLAYER_STATUS_UNSPECIFIED PlayerStatus = 0
	PlayerStatus_PLAYER_STATUS_WAITING     PlayerStatus = 1
	PlayerStatus_PLAYER_STATUS_READY       PlayerStatus = 2
	PlayerStatus_PLAYER_STATUS_PLAYING     PlayerStatus = 3
	PlayerStatus_PLAYER_STATUS_FINISHED    PlayerStatus = 4
)

// Enum value maps for PlayerStatus.
var (
	PlayerStatus_name = map[int32]string{
		0: "PLAYER_STATUS_UNSPECIFIED",
		1: "PLAYER_STATUS_WAITING",
		2: "PLAYER_STATUS_READY",
		3: "PLAYER_STATUS_PLAYING",
		4: "PLAYER_STATUS_FINISHED",
	}
	PlayerStatus_value = map[string]int32{
		"PLAYER_STATUS_UNSPECIFIED": 0,
		"PLAYER_STATUS_WAITING":     1,
		"PLAYER_STATUS_READY":       2,
		"PLAYER_STATUS_PLAYING":     3,
		"PLAYER_STATUS_FINISHED":    4,
	}
)

func (x PlayerStatus) Enum() *PlayerStatus {
	p := new(PlayerStatus)
	*p = x
	return p
}

func (x PlayerStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlayerStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_room_proto_enumTypes[2].Descriptor()
}

func (PlayerStatus) Type() protoreflect.EnumType {
	return &file_room_proto_enumTypes[2]
}

func (x PlayerStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlayerStatus.Descriptor instead.
func (PlayerStatus) EnumDescriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{2}
}

// PlayerResult represents the result of a player in a round
type PlayerResult int32

const (
	PlayerResult_PLAYER_RESULT_UNSPECIFIED PlayerResult = 0
	PlayerResult_PLAYER_RESULT_WON         PlayerResult = 1
	PlayerResult_PLAYER_RESULT_LOST        PlayerResult = 2
)

// Enum value maps for PlayerResult.
var (
	PlayerResult_name = map[int32]string{
		0: "PLAYER_RESULT_UNSPECIFIED",
		1: "PLAYER_RESULT_WON",
		2: "PLAYER_RESULT_LOST",
	}
	PlayerResult_value = map[string]int32{
		"PLAYER_RESULT_UNSPECIFIED": 0,
		"PLAYER_RESULT_WON":         1,
		"PLAYER_RESULT_LOST":        2,
	}
)

func (x PlayerResult) Enum() *PlayerResult {
	p := new(PlayerResult)
	*p = x
	return p
}

func (x PlayerResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlayerResult) Descriptor() protoreflect.EnumDescriptor {
	return file_room_proto_enumTypes[3].Descriptor()
}

func (PlayerResult) Type() protoreflect.EnumType {
	return &file_room_proto_enumTypes[3]
}

func (x PlayerResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlayerResult.Descriptor instead.
func (PlayerResult) EnumDescriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{3}
}

// LetterResult represents the result of a letter in a guess
type LetterResult int32

const (
	LetterResult_LETTER_RESULT_UNSPECIFIED LetterResult = 0
	LetterResult_LETTER_RESULT_CORRECT     LetterResult = 1
	LetterResult_LETTER_RESULT_PRESENT     LetterResult = 2
	LetterResult_LETTER_RESULT_ABSENT      LetterResult = 3
)

// Enum value maps for LetterResult.
var (
	LetterResult_name = map[int32]string{
		0: "LETTER_RESULT_UNSPECIFIED",
		1: "LETTER_RESULT_CORRECT",
		2: "LETTER_RESULT_PRESENT",
		3: "LETTER_RESULT_ABSENT",
	}
	LetterResult_value = map[string]int32{
		"LETTER_RESULT_UNSPECIFIED": 0,
		"LETTER_RESULT_CORRECT":     1,
		"LETTER_RESULT_PRESENT":     2,
		"LETTER_RESULT_ABSENT":      3,
	}
)

func (x LetterResult) Enum() *LetterResult {
	p := new(LetterResult)
	*p = x
	return p
}

func (x LetterResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LetterResult) Descriptor() protoreflect.EnumDescriptor {
	return file_room_proto_enumTypes[4].Descriptor()
}

func (LetterResult) Type() protoreflect.EnumType {
	return &file_room_proto_enumTypes[4]
}

func (x LetterResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LetterResult.Descriptor instead.
func (LetterResult) EnumDescriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{4}
}

// RoomSettings contains the settings for a room
type RoomSettings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          RoomMode               `protobuf:"varint,1,opt,name=mode,proto3,enum=room.v1.RoomMode" json:"mode,omitempty"`
	MaxPlayers    int32                  `protobuf:"varint,2,opt,name=max_players,json=maxPlayers,proto3" json:"max_players,omitempty"`
	TimeLimitSecs int32                  `protobuf:"varint,3,opt,name=time_limit_secs,json=timeLimitSecs,proto3" json:"time_limit_secs,omitempty"` // For marathon mode
	ShowGuesses   bool                   `protobuf:"varint,4,opt,name=show_guesses,json=showGuesses,proto3" json:"show_guesses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomSettings) Reset() {
	*x = RoomSettings{}
	mi := &file_room_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomSettings) ProtoMessage() {}

func (x *RoomSettings) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomSettings.ProtoReflect.Descriptor instead.
func (*RoomSettings) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{0}
}

func (x *RoomSettings) GetMode() RoomMode {
	if x != nil {
		return x.Mode
	}
	return RoomMode_ROOM_MODE_UNSPECIFIED
}

func (x *RoomSettings) GetMaxPlayers() int32 {
	if x != nil {
		return x.MaxPlayers
	}
	return 0
}

func (x *RoomSettings) GetTimeLimitSecs() int32 {
	if x != nil {
		return x.TimeLimitSecs
	}
	return 0
}

func (x *RoomSettings) GetShowGuesses() bool {
	if x != nil {
		return x.ShowGuesses
	}
	return false
}

// Room represents a multiplayer room
type Room struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	HostId        string                 `protobuf:"bytes,3,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Status        RoomStatus             `protobuf:"varint,4,opt,name=status,proto3,enum=room.v1.RoomStatus" json:"status,omitempty"`
	Settings      *RoomSettings          `protobuf:"bytes,5,opt,name=settings,proto3" json:"settings,omitempty"`
	RoundNumber   int32                  `protobuf:"varint,6,opt,name=round_number,json=roundNumber,proto3" json:"round_number,omitempty"`
	Language      string                 `protobuf:"bytes,7,opt,name=language,proto3" json:"language,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpiresAt     string                 `protobuf:"bytes,9,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Room) Reset() {
	*x = Room{}
	mi := &file_room_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Room) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Room) ProtoMessage() {}

func (x *Room) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Room.ProtoReflect.Descriptor instead.
func (*Room) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{1}
}

func (x *Room) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Room) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Room) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *Room) GetStatus() RoomStatus {
	if x != nil {
		return x.Status
	}
	return RoomStatus_ROOM_STATUS_UNSPECIFIED
}

func (x *Room) GetSettings() *RoomSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *Room) GetRoundNumber() int32 {
	if x != nil {
		return x.RoundNumber
	}
	return 0
}

func (x *Room) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *Room) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Room) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

// Guess represents a single guess
type Guess struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Word          string                 `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
	Results       []LetterResult         `protobuf:"varint,2,rep,packed,name=results,proto3,enum=room.v1.LetterResult" json:"results,omitempty"`
	AttemptNumber int32                  `protobuf:"varint,3,opt,name=attempt_number,json=attemptNumber,proto3" json:"attempt_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Guess) Reset() {
	*x = Guess{}
	mi := &file_room_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Guess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Guess) ProtoMessage() {}

func (x *Guess) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Guess.ProtoReflect.Descriptor instead.
func (*Guess) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{2}
}

func (x *Guess) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

func (x *Guess) GetResults() []LetterResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *Guess) GetAttemptNumber() int32 {
	if x != nil {
		return x.AttemptNumber
	}
	return 0
}

// RoomPlayer represents a player in a room
type RoomPlayer struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PlayerId        string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	UserId          string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	GuestId         string                 `protobuf:"bytes,3,opt,name=guest_id,json=guestId,proto3" json:"guest_id,omitempty"`
	DisplayName     string                 `protobuf:"bytes,4,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Status          PlayerStatus           `protobuf:"varint,5,opt,name=status,proto3,enum=room.v1.PlayerStatus" json:"status,omitempty"`
	Result          PlayerResult           `protobuf:"varint,6,opt,name=result,proto3,enum=room.v1.PlayerResult" json:"result,omitempty"`
	CurrentAttempts int32                  `protobuf:"varint,7,opt,name=current_attempts,json=currentAttempts,proto3" json:"current_attempts,omitempty"`
	TotalScore      int32                  `protobuf:"varint,8,opt,name=total_score,json=totalScore,proto3" json:"total_score,omitempty"`
	Guesses         []*Guess               `protobuf:"bytes,9,rep,name=guesses,proto3" json:"guesses,omitempty"`
	FinishedAt      string                 `protobuf:"bytes,10,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RoomPlayer) Reset() {
	*x = RoomPlayer{}
	mi := &file_room_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomPlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomPlayer) ProtoMessage() {}

func (x *RoomPlayer) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomPlayer.ProtoReflect.Descriptor instead.
func (*RoomPlayer) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{3}
}

func (x *RoomPlayer) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *RoomPlayer) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RoomPlayer) GetGuestId() string {
	if x != nil {
		return x.GuestId
	}
	return ""
}

func (x *RoomPlayer) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *RoomPlayer) GetStatus() PlayerStatus {
	if x != nil {
		return x.Status
	}
	return PlayerStatus_PLAYER_STATUS_UNSPECIFIED
}

func (x *RoomPlayer) GetResult() PlayerResult {
	if x != nil {
		return x.Result
	}
	return PlayerResult_PLAYER_RESULT_UNSPECIFIED
}

func (x *RoomPlayer) GetCurrentAttempts() int32 {
	if x != nil {
		return x.CurrentAttempts
	}
	return 0
}

func (x *RoomPlayer) GetTotalScore() int32 {
	if x != nil {
		return x.TotalScore
	}
	return 0
}

func (x *RoomPlayer) GetGuesses() []*Guess {
	if x != nil {
		return x.Guesses
	}
	return nil
}

func (x *RoomPlayer) GetFinishedAt() string {
	if x != nil {
		return x.FinishedAt
	}
	return ""
}

// CreateRoomRequest is the request to create a new room
type CreateRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settings      *RoomSettings          `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings,omitempty"`
	Language      string                 `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomRequest) Reset() {
	*x = CreateRoomRequest{}
	mi := &file_room_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomRequest) ProtoMessage() {}

func (x *CreateRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomRequest.ProtoReflect.Descriptor instead.
func (*CreateRoomRequest) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{4}
}

func (x *CreateRoomRequest) GetSettings() *RoomSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *CreateRoomRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

// CreateRoomResponse is the response for room creation
type CreateRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Room          *Room                  `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomResponse) Reset() {
	*x = CreateRoomResponse{}
	mi := &file_room_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomResponse) ProtoMessage() {}

func (x *CreateRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomResponse.ProtoReflect.Descriptor instead.
func (*CreateRoomResponse) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{5}
}

func (x *CreateRoomResponse) GetRoom() *Room {
	if x != nil {
		return x.Room
	}
	return nil
}

// GetRoomRequest is the request to get a room
type GetRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomRequest) Reset() {
	*x = GetRoomRequest{}
	mi := &file_room_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomRequest) ProtoMessage() {}

func (x *GetRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomRequest.ProtoReflect.Descriptor instead.
func (*GetRoomRequest) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{6}
}

func (x *GetRoomRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

// GetRoomResponse is the response for getting a room
type GetRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Room          *Room                  `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	Players       []*RoomPlayer          `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomResponse) Reset() {
	*x = GetRoomResponse{}
	mi := &file_room_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomResponse) ProtoMessage() {}

func (x *GetRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomResponse.ProtoReflect.Descriptor instead.
func (*GetRoomResponse) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{7}
}

func (x *GetRoomResponse) GetRoom() *Room {
	if x != nil {
		return x.Room
	}
	return nil
}

func (x *GetRoomResponse) GetPlayers() []*RoomPlayer {
	if x != nil {
		return x.Players
	}
	return nil
}

// JoinRoomRequest is the request to join a room
type JoinRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	GuestId       string                 `protobuf:"bytes,2,opt,name=guest_id,json=guestId,proto3" json:"guest_id,omitempty"` // Required for guests
	DisplayName   string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRoomRequest) Reset() {
	*x = JoinRoomRequest{}
	mi := &file_room_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomRequest) ProtoMessage() {}

func (x *JoinRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoomRequest.ProtoReflect.Descriptor instead.
func (*JoinRoomRequest) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{8}
}

func (x *JoinRoomRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *JoinRoomRequest) GetGuestId() string {
	if x != nil {
		return x.GuestId
	}
	return ""
}

func (x *JoinRoomRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

// JoinRoomResponse is the response for joining a room
type JoinRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Room          *Room                  `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	Player        *RoomPlayer            `protobuf:"bytes,2,opt,name=player,proto3" json:"player,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRoomResponse) Reset() {
	*x = JoinRoomResponse{}
	mi := &file_room_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomResponse) ProtoMessage() {}

func (x *JoinRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoomResponse.ProtoReflect.Descriptor instead.
func (*JoinRoomResponse) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{9}
}

func (x *JoinRoomResponse) GetRoom() *Room {
	if x != nil {
		return x.Room
	}
	return nil
}

func (x *JoinRoomResponse) GetPlayer() *RoomPlayer {
	if x != nil {
		return x.Player
	}
	return nil
}

// LeaveRoomRequest is the request to leave a room
type LeaveRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveRoomRequest) Reset() {
	*x = LeaveRoomRequest{}
	mi := &file_room_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRoomRequest) ProtoMessage() {}

func (x *LeaveRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRoomRequest.ProtoReflect.Descriptor instead.
func (*LeaveRoomRequest) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{10}
}

func (x *LeaveRoomRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

// LeaveRoomResponse is the response for leaving a room
type LeaveRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveRoomResponse) Reset() {
	*x = LeaveRoomResponse{}
	mi := &file_room_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRoomResponse) ProtoMessage() {}

func (x *LeaveRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRoomResponse.ProtoReflect.Descriptor instead.
func (*LeaveRoomResponse) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{11}
}

func (x *LeaveRoomResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// SetReadyRequest is the request to set ready status
type SetReadyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Ready         bool                   `protobuf:"varint,2,opt,name=ready,proto3" json:"ready,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetReadyRequest) Reset() {
	*x = SetReadyRequest{}
	mi := &file_room_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetReadyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetReadyRequest) ProtoMessage() {}

func (x *SetReadyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetReadyRequest.ProtoReflect.Descriptor instead.
func (*SetReadyRequest) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{12}
}

func (x *SetReadyRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *SetReadyRequest) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

// SetReadyResponse is the response for setting ready status
type SetReadyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetReadyResponse) Reset() {
	*x = SetReadyResponse{}
	mi := &file_room_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetReadyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetReadyResponse) ProtoMessage() {}

func (x *SetReadyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetReadyResponse.ProtoReflect.Descriptor instead.
func (*SetReadyResponse) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{13}
}

func (x *SetReadyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// StartGameRequest is the request to start a room game
type StartGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartGameRequest) Reset() {
	*x = StartGameRequest{}
	mi := &file_room_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartGameRequest) ProtoMessage() {}

func (x *StartGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartGameRequest.ProtoReflect.Descriptor instead.
func (*StartGameRequest) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{14}
}

func (x *StartGameRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

// StartGameResponse is the response for starting a room game
type StartGameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Room          *Room                  `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartGameResponse) Reset() {
	*x = StartGameResponse{}
	mi := &file_room_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartGameResponse) ProtoMessage() {}

func (x *StartGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartGameResponse.ProtoReflect.Descriptor instead.
func (*StartGameResponse) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{15}
}

func (x *StartGameResponse) GetRoom() *Room {
	if x != nil {
		return x.Room
	}
	return nil
}

// SubmitGuessRequest is the request to submit a guess in a room
type SubmitGuessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Word          string                 `protobuf:"bytes,2,opt,name=word,proto3" json:"word,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitGuessRequest) Reset() {
	*x = SubmitGuessRequest{}
	mi := &file_room_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitGuessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitGuessRequest) ProtoMessage() {}

func (x *SubmitGuessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitGuessRequest.ProtoReflect.Descriptor instead.
func (*SubmitGuessRequest) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{16}
}

func (x *SubmitGuessRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *SubmitGuessRequest) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

// SubmitGuessResponse is the response for a room guess
type SubmitGuessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Guess         *Guess                 `protobuf:"bytes,1,opt,name=guess,proto3" json:"guess,omitempty"`
	Player        *RoomPlayer            `protobuf:"bytes,2,opt,name=player,proto3" json:"player,omitempty"`
	Room          *Room                  `protobuf:"bytes,3,opt,name=room,proto3" json:"room,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitGuessResponse) Reset() {
	*x = SubmitGuessResponse{}
	mi := &file_room_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitGuessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitGuessResponse) ProtoMessage() {}

func (x *SubmitGuessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitGuessResponse.ProtoReflect.Descriptor instead.
func (*SubmitGuessResponse) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{17}
}

func (x *SubmitGuessResponse) GetGuess() *Guess {
	if x != nil {
		return x.Guess
	}
	return nil
}

func (x *SubmitGuessResponse) GetPlayer() *RoomPlayer {
	if x != nil {
		return x.Player
	}
	return nil
}

func (x *SubmitGuessResponse) GetRoom() *Room {
	if x != nil {
		return x.Room
	}
	return nil
}

// NextRoundRequest is the request to start the next round
type NextRoundRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NextRoundRequest) Reset() {
	*x = NextRoundRequest{}
	mi := &file_room_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NextRoundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NextRoundRequest) ProtoMessage() {}

func (x *NextRoundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NextRoundRequest.ProtoReflect.Descriptor instead.
func (*NextRoundRequest) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{18}
}

func (x *NextRoundRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

// NextRoundResponse is the response for starting the next round
type NextRoundResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Room          *Room                  `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NextRoundResponse) Reset() {
	*x = NextRoundResponse{}
	mi := &file_room_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NextRoundResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NextRoundResponse) ProtoMessage() {}

func (x *NextRoundResponse) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NextRoundResponse.ProtoReflect.Descriptor instead.
func (*NextRoundResponse) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{19}
}

func (x *NextRoundResponse) GetRoom() *Room {
	if x != nil {
		return x.Room
	}
	return nil
}

var File_room_proto protoreflect.FileDescriptor

const file_room_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"room.proto\x12\aroom.v1\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xa1\x01\n" +
	"\fRoomSettings\x12%\n" +
	"\x04mode\x18\x01 \x01(\x0e2\x11.room.v1.RoomModeR\x04mode\x12\x1f\n" +
	"\vmax_players\x18\x02 \x01(\x05R\n" +
	"maxPlayers\x12&\n" +
	"\x0ftime_limit_secs\x18\x03 \x01(\x05R\rtimeLimitSecs\x12!\n" +
	"\fshow_guesses\x18\x04 \x01(\bR\vshowGuesses\"\xa0\x02\n" +
	"\x04Room\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x17\n" +
	"\ahost_id\x18\x03 \x01(\tR\x06hostId\x12+\n" +
	"\x06status\x18\x04 \x01(\x0e2\x13.room.v1.RoomStatusR\x06status\x121\n" +
	"\bsettings\x18\x05 \x01(\v2\x15.room.v1.RoomSettingsR\bsettings\x12!\n" +
	"\fround_number\x18\x06 \x01(\x05R\vroundNumber\x12\x1a\n" +
	"\blanguage\x18\a \x01(\tR\blanguage\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\t \x01(\tR\texpiresAt\"s\n" +
	"\x05Guess\x12\x12\n" +
	"\x04word\x18\x01 \x01(\tR\x04word\x12/\n" +
	"\aresults\x18\x02 \x03(\x0e2\x15.room.v1.LetterResultR\aresults\x12%\n" +
	"\x0eattempt_number\x18\x03 \x01(\x05R\rattemptNumber\"\xf5\x02\n" +
	"\n" +
	"RoomPlayer\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x19\n" +
	"\bguest_id\x18\x03 \x01(\tR\aguestId\x12!\n" +
	"\fdisplay_name\x18\x04 \x01(\tR\vdisplayName\x12-\n" +
	"\x06status\x18\x05 \x01(\x0e2\x15.room.v1.PlayerStatusR\x06status\x12-\n" +
	"\x06result\x18\x06 \x01(\x0e2\x15.room.v1.PlayerResultR\x06result\x12)\n" +
	"\x10current_attempts\x18\a \x01(\x05R\x0fcurrentAttempts\x12\x1f\n" +
	"\vtotal_score\x18\b \x01(\x05R\n" +
	"totalScore\x12(\n" +
	"\aguesses\x18\t \x03(\v2\x0e.room.v1.GuessR\aguesses\x12\x1f\n" +
	"\vfinished_at\x18\n" +
	" \x01(\tR\n" +
	"finishedAt\"b\n" +
	"\x11CreateRoomRequest\x121\n" +
	"\bsettings\x18\x01 \x01(\v2\x15.room.v1.RoomSettingsR\bsettings\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\"7\n" +
	"\x12CreateRoomResponse\x12!\n" +
	"\x04room\x18\x01 \x01(\v2\r.room.v1.RoomR\x04room\"$\n" +
	"\x0eGetRoomRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"c\n" +
	"\x0fGetRoomResponse\x12!\n" +
	"\x04room\x18\x01 \x01(\v2\r.room.v1.RoomR\x04room\x12-\n" +
	"\aplayers\x18\x02 \x03(\v2\x13.room.v1.RoomPlayerR\aplayers\"c\n" +
	"\x0fJoinRoomRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x19\n" +
	"\bguest_id\x18\x02 \x01(\tR\aguestId\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\"b\n" +
	"\x10JoinRoomResponse\x12!\n" +
	"\x04room\x18\x01 \x01(\v2\r.room.v1.RoomR\x04room\x12+\n" +
	"\x06player\x18\x02 \x01(\v2\x13.room.v1.RoomPlayerR\x06player\"&\n" +
	"\x10LeaveRoomRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"-\n" +
	"\x11LeaveRoomResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\";\n" +
	"\x0fSetReadyRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x14\n" +
	"\x05ready\x18\x02 \x01(\bR\x05ready\",\n" +
	"\x10SetReadyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"&\n" +
	"\x10StartGameRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"6\n" +
	"\x11StartGameResponse\x12!\n" +
	"\x04room\x18\x01 \x01(\v2\r.room.v1.RoomR\x04room\"<\n" +
	"\x12SubmitGuessRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04word\x18\x02 \x01(\tR\x04word\"\x8b\x01\n" +
	"\x13SubmitGuessResponse\x12$\n" +
	"\x05guess\x18\x01 \x01(\v2\x0e.room.v1.GuessR\x05guess\x12+\n" +
	"\x06player\x18\x02 \x01(\v2\x13.room.v1.RoomPlayerR\x06player\x12!\n" +
	"\x04room\x18\x03 \x01(\v2\r.room.v1.RoomR\x04room\"&\n" +
	"\x10NextRoundRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"6\n" +
	"\x11NextRoundResponse\x12!\n" +
	"\x04room\x18\x01 \x01(\v2\r.room.v1.RoomR\x04room*Y\n" +
	"\bRoomMode\x12\x19\n" +
	"\x15ROOM_MODE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16ROOM_MODE_SINGLE_ROUND\x10\x01\x12\x16\n" +
	"\x12ROOM_MODE_MARATHON\x10\x02*u\n" +
	"\n" +
	"RoomStatus\x12\x1b\n" +
	"\x17ROOM_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13ROOM_STATUS_WAITING\x10\x01\x12\x17\n" +
	"\x13ROOM_STATUS_PLAYING\x10\x02\x12\x18\n" +
	"\x14ROOM_STATUS_FINISHED\x10\x03*\x98\x01\n" +
	"\fPlayerStatus\x12\x1d\n" +
	"\x19PLAYER_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15PLAYER_STATUS_WAITING\x10\x01\x12\x17\n" +
	"\x13PLAYER_STATUS_READY\x10\x02\x12\x19\n" +
	"\x15PLAYER_STATUS_PLAYING\x10\x03\x12\x1a\n" +
	"\x16PLAYER_STATUS_FINISHED\x10\x04*\\\n" +
	"\fPlayerResult\x12\x1d\n" +
	"\x19PLAYER_RESULT_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11PLAYER_RESULT_WON\x10\x01\x12\x16\n" +
	"\x12PLAYER_RESULT_LOST\x10\x02*}\n" +
	"\fLetterResult\x12\x1d\n" +
	"\x19LETTER_RESULT_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15LETTER_RESULT_CORRECT\x10\x01\x12\x19\n" +
	"\x15LETTER_RESULT_PRESENT\x10\x02\x12\x18\n" +
	"\x14LETTER_RESULT_ABSENT\x10\x032\xdc\x06\n" +
	"\vRoomService\x12t\n" +
	"\n" +
	"CreateRoom\x12\x1a.room.v1.CreateRoomRequest\x1a\x1b.room.v1.CreateRoomResponse\"-\x92A\x12b\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/api/v1/rooms\x12Z\n" +
	"\aGetRoom\x12\x17.room.v1.GetRoomRequest\x1a\x18.room.v1.GetRoomResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/api/v1/rooms/{code}\x12e\n" +
	"\bJoinRoom\x12\x18.room.v1.JoinRoomRequest\x1a\x19.room.v1.JoinRoomResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/api/v1/rooms/{code}/join\x12f\n" +
	"\tLeaveRoom\x12\x19.room.v1.LeaveRoomRequest\x1a\x1a.room.v1.LeaveRoomResponse\"\"\x82\xd3\xe4\x93\x02\x1c*\x1a/api/v1/rooms/{code}/leave\x12f\n" +
	"\bSetReady\x12\x18.room.v1.SetReadyRequest\x1a\x19.room.v1.SetReadyResponse\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/api/v1/rooms/{code}/ready\x12i\n" +
	"\tStartGame\x12\x19.room.v1.StartGameRequest\x1a\x1a.room.v1.StartGameResponse\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/api/v1/rooms/{code}/start\x12o\n" +
	"\vSubmitGuess\x12\x1b.room.v1.SubmitGuessRequest\x1a\x1c.room.v1.SubmitGuessResponse\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/api/v1/rooms/{code}/guess\x12h\n" +
	"\tNextRound\x12\x19.room.v1.NextRoundRequest\x1a\x1a.room.v1.NextRoundResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/api/v1/rooms/{code}/nextB)Z'gordle/game/pkg/protogen/room/v1;roomv1b\x06proto3"

var (
	file_room_proto_rawDescOnce sync.Once
	file_room_proto_rawDescData []byte
)

func file_room_proto_rawDescGZIP() []byte {
	file_room_proto_rawDescOnce.Do(func() {
		file_room_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_room_proto_rawDesc), len(file_room_proto_rawDesc)))
	})
	return file_room_proto_rawDescData
}

var file_room_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_room_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_room_proto_goTypes = []any{
	(RoomMode)(0),               // 0: room.v1.RoomMode
	(RoomStatus)(0),             // 1: room.v1.RoomStatus
	(PlayerStatus)(0),           // 2: room.v1.PlayerStatus
	(PlayerResult)(0),           // 3: room.v1.PlayerResult
	(LetterResult)(0),           // 4: room.v1.LetterResult
	(*RoomSettings)(nil),        // 5: room.v1.RoomSettings
	(*Room)(nil),                // 6: room.v1.Room
	(*Guess)(nil),               // 7: room.v1.Guess
	(*RoomPlayer)(nil),          // 8: room.v1.RoomPlayer
	(*CreateRoomRequest)(nil),   // 9: room.v1.CreateRoomRequest
	(*CreateRoomResponse)(nil),  // 10: room.v1.CreateRoomResponse
	(*GetRoomRequest)(nil),      // 11: room.v1.GetRoomRequest
	(*GetRoomResponse)(nil),     // 12: room.v1.GetRoomResponse
	(*JoinRoomRequest)(nil),     // 13: room.v1.JoinRoomRequest
	(*JoinRoomResponse)(nil),    // 14: room.v1.JoinRoomResponse
	(*LeaveRoomRequest)(nil),    // 15: room.v1.LeaveRoomRequest
	(*LeaveRoomResponse)(nil),   // 16: room.v1.LeaveRoomResponse
	(*SetReadyRequest)(nil),     // 17: room.v1.SetReadyRequest
	(*SetReadyResponse)(nil),    // 18: room.v1.SetReadyResponse
	(*StartGameRequest)(nil),    // 19: room.v1.StartGameRequest
	(*StartGameResponse)(nil),   // 20: room.v1.StartGameResponse
	(*SubmitGuessRequest)(nil),  // 21: room.v1.SubmitGuessRequest
	(*SubmitGuessResponse)(nil), // 22: room.v1.SubmitGuessResponse
	(*NextRoundRequest)(nil),    // 23: room.v1.NextRoundRequest
	(*NextRoundResponse)(nil),   // 24: room.v1.NextRoundResponse
}
var file_room_proto_depIdxs = []int32{
	0,  // 0: room.v1.RoomSettings.mode:type_name -> room.v1.RoomMode
	1,  // 1: room.v1.Room.status:type_name -> room.v1.RoomStatus
	5,  // 2: room.v1.Room.settings:type_name -> room.v1.RoomSettings
	4,  // 3: room.v1.Guess.results:type_name -> room.v1.LetterResult
	2,  // 4: room.v1.RoomPlayer.status:type_name -> room.v1.PlayerStatus
	3,  // 5: room.v1.RoomPlayer.result:type_name -> room.v1.PlayerResult
	7,  // 6: room.v1.RoomPlayer.guesses:type_name -> room.v1.Guess
	5,  // 7: room.v1.CreateRoomRequest.settings:type_name -> room.v1.RoomSettings
	6,  // 8: room.v1.CreateRoomResponse.room:type_name -> room.v1.Room
	6,  // 9: room.v1.GetRoomResponse.room:type_name -> room.v1.Room
	8,  // 10: room.v1.GetRoomResponse.players:type_name -> room.v1.RoomPlayer
	6,  // 11: room.v1.JoinRoomResponse.room:type_name -> room.v1.Room
	8,  // 12: room.v1.JoinRoomResponse.player:type_name -> room.v1.RoomPlayer
	6,  // 13: room.v1.StartGameResponse.room:type_name -> room.v1.Room
	7,  // 14: room.v1.SubmitGuessResponse.guess:type_name -> room.v1.Guess
	8,  // 15: room.v1.SubmitGuessResponse.player:type_name -> room.v1.RoomPlayer
	6,  // 16: room.v1.SubmitGuessResponse.room:type_name -> room.v1.Room
	6,  // 17: room.v1.NextRoundResponse.room:type_name -> room.v1.Room
	9,  // 18: room.v1.RoomService.CreateRoom:input_type -> room.v1.CreateRoomRequest
	11, // 19: room.v1.RoomService.GetRoom:input_type -> room.v1.GetRoomRequest
	13, // 20: room.v1.RoomService.JoinRoom:input_type -> room.v1.JoinRoomRequest
	15, // 21: room.v1.RoomService.LeaveRoom:input_type -> room.v1.LeaveRoomRequest
	17, // 22: room.v1.RoomService.SetReady:input_type -> room.v1.SetReadyRequest
	19, // 23: room.v1.RoomService.StartGame:input_type -> room.v1.StartGameRequest
	21, // 24: room.v1.RoomService.SubmitGuess:input_type -> room.v1.SubmitGuessRequest
	23, // 25: room.v1.RoomService.NextRound:input_type -> room.v1.NextRoundRequest
	10, // 26: room.v1.RoomService.CreateRoom:output_type -> room.v1.CreateRoomResponse
	12, // 27: room.v1.RoomService.GetRoom:output_type -> room.v1.GetRoomResponse
	14, // 28: room.v1.RoomService.JoinRoom:output_type -> room.v1.JoinRoomResponse
	16, // 29: room.v1.RoomService.LeaveRoom:output_type -> room.v1.LeaveRoomResponse
	18, // 30: room.v1.RoomService.SetReady:output_type -> room.v1.SetReadyResponse
	20, // 31: room.v1.RoomService.StartGame:output_type -> room.v1.StartGameResponse
	22, // 32: room.v1.RoomService.SubmitGuess:output_type -> room.v1.SubmitGuessResponse
	24, // 33: room.v1.RoomService.NextRound:output_type -> room.v1.NextRoundResponse
	26, // [26:34] is the sub-list for method output_type
	18, // [18:26] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_room_proto_init() }
func file_room_proto_init() {
	if File_room_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_room_proto_rawDesc), len(file_room_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_room_proto_goTypes,
		DependencyIndexes: file_room_proto_depIdxs,
		EnumInfos:         file_room_proto_enumTypes,
		MessageInfos:      file_room_proto_msgTypes,
	}.Build()
	File_room_proto = out.File
	file_room_proto_goTypes = nil
	file_room_proto_depIdxs = nil
}
